//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IAS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่สอบ(เริ่ม) ต้องน้อยกว่าหรือเท่า วันที่สอบ(สิ้นสุด).
        /// </summary>
        public static string errorApplicantDetail_StartExamDateMoreThanEndExamDate {
            get {
                return ResourceManager.GetString("errorApplicantDetail_StartExamDateMoreThanEndExamDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่มีรายการที่เลือก.
        /// </summary>
        public static string errorApplicantNoPay_003 {
            get {
                return ResourceManager.GetString("errorApplicantNoPay_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่(เริ่ม) ต้องน้อยกว่าหรือเท่า วันที่(สิ้นสุด).
        /// </summary>
        public static string errorApplicantNoPay_004 {
            get {
                return ResourceManager.GetString("errorApplicantNoPay_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทำรายการไม่สำเร็จ.
        /// </summary>
        public static string errorChangePass_001 {
            get {
                return ResourceManager.GetString("errorChangePass_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกสถานะอนุมัติ.
        /// </summary>
        public static string errorEdit_Reg_Person_004 {
            get {
                return ResourceManager.GetString("errorEdit_Reg_Person_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถสร้างกำหนดการย้อนหลัง.
        /// </summary>
        public static string errorExamSchedule_001 {
            get {
                return ResourceManager.GetString("errorExamSchedule_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เกิดความผิดพลาดกับข้อมูล โปรดตรวจสอบข้อมูลในไฟล์อีกครั้ง!.
        /// </summary>
        public static string errorFS030_001 {
            get {
                return ResourceManager.GetString("errorFS030_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกไฟล์ข้อมูลที่ต้องการ ก่อนจะนำข้อมูลเข้า.
        /// </summary>
        public static string errorFS030_002 {
            get {
                return ResourceManager.GetString("errorFS030_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกไฟล์ไม่ถูกประเภท ต้องเลือกเฉพาะประเภทที่มีนามสกุลเป็น(.txt).
        /// </summary>
        public static string errorFS030_003 {
            get {
                return ResourceManager.GetString("errorFS030_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พบข้อผิดพลาด กรุณาติดต่อเจ้าหน้าที่ผู้ดูแลระบบ.
        /// </summary>
        public static string errorGenPayment_002 {
            get {
                return ResourceManager.GetString("errorGenPayment_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบข้อมูล.
        /// </summary>
        public static string errorGenPayment_003 {
            get {
                return ResourceManager.GetString("errorGenPayment_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกประเภทใบสั่งจ่าย.
        /// </summary>
        public static string errorInvoice_002 {
            get {
                return ResourceManager.GetString("errorInvoice_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ท่านยังไม่ได้เลือกใบสั่งจ่าย.
        /// </summary>
        public static string errorInvoice5_001 {
            get {
                return ResourceManager.GetString("errorInvoice5_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกรายการที่ต้องการดำเนินการก่อนทำรายการต่อ.
        /// </summary>
        public static string errorLicenseContinue_001 {
            get {
                return ResourceManager.GetString("errorLicenseContinue_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบเลขบัตรประชาชนในการทำรายการ.
        /// </summary>
        public static string errorLicenseDetail_001 {
            get {
                return ResourceManager.GetString("errorLicenseDetail_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พบข้อมูลผิดพลาดไม่สามารถทำรายการได้..
        /// </summary>
        public static string errorLicenseGroup_001 {
            get {
                return ResourceManager.GetString("errorLicenseGroup_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่มีข้อมูลรายละเอียด.
        /// </summary>
        public static string errorLicenseGroup_002 {
            get {
                return ResourceManager.GetString("errorLicenseGroup_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มีข้อมูลการขอรับใบอนุญาตที่ยังไม่ถูกต้องอยู่ ไม่สามารถนำเข้าข้อมูลได้.
        /// </summary>
        public static string errorLicenseGroup_003 {
            get {
                return ResourceManager.GetString("errorLicenseGroup_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบการทำรายการปัจจุบัน.
        /// </summary>
        public static string errorMasterLicense_001 {
            get {
                return ResourceManager.GetString("errorMasterLicense_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบผู้ใช้งานปัจจุบัน.
        /// </summary>
        public static string errorMasterRegister_001 {
            get {
                return ResourceManager.GetString("errorMasterRegister_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณไม่ได้เลือกรายการ.
        /// </summary>
        public static string errorPaymentDetail_001 {
            get {
                return ResourceManager.GetString("errorPaymentDetail_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถดำเนินการได้.
        /// </summary>
        public static string errorPaymentDetail_002 {
            get {
                return ResourceManager.GetString("errorPaymentDetail_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถนำเข้าข้อมูลได้ เนื่องจาก มีรายการข้อมูลไม่ถูกต้อง!!!.
        /// </summary>
        public static string errorPayRenewFee_001 {
            get {
                return ResourceManager.GetString("errorPayRenewFee_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลผิดพลาด.
        /// </summary>
        public static string errorPayRenewFee_003 {
            get {
                return ResourceManager.GetString("errorPayRenewFee_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไฟล์ต้องเป็นไฟล์รูปภาพ และ เป็นชนิด png เท่านั้น.
        /// </summary>
        public static string errorReg_OIC_001 {
            get {
                return ResourceManager.GetString("errorReg_OIC_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ท่านได้ทำการอนุมัติกลุ่มไม่สำเร็จ.
        /// </summary>
        public static string errorReg_OIC_Search_001 {
            get {
                return ResourceManager.GetString("errorReg_OIC_Search_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ท่านได้ทำการอนุมัติกลุ่มเรียบร้อยแล้วครับ.
        /// </summary>
        public static string errorReg_OIC_Search_002 {
            get {
                return ResourceManager.GetString("errorReg_OIC_Search_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบรหัสเอกสารที่ระบุ..
        /// </summary>
        public static string errorReg_Person_t_001 {
            get {
                return ResourceManager.GetString("errorReg_Person_t_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกคุณวุฒิ.
        /// </summary>
        public static string errorRegisGeneral_001 {
            get {
                return ResourceManager.GetString("errorRegisGeneral_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณวุฒิที่เลือกมีในรายการแล้ว.
        /// </summary>
        public static string errorRegisGeneral_002 {
            get {
                return ResourceManager.GetString("errorRegisGeneral_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่อยู่ปัจจุบัน กรุณากรอกที่อยู่.
        /// </summary>
        public static string errorRegisGeneral_ucAddressCurrent_errorAddressRequired {
            get {
                return ResourceManager.GetString("errorRegisGeneral_ucAddressCurrent_errorAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่อยู่ปัจจุบัน กรุณาเลือกอำเภอ.
        /// </summary>
        public static string errorRegisGeneral_ucAddressCurrent_errorDistrictAddressRequired {
            get {
                return ResourceManager.GetString("errorRegisGeneral_ucAddressCurrent_errorDistrictAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่อยู่ปัจจุบัน กรุณาเลือกตำบล.
        /// </summary>
        public static string errorRegisGeneral_ucAddressCurrent_errorParishAddressRequired {
            get {
                return ResourceManager.GetString("errorRegisGeneral_ucAddressCurrent_errorParishAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่อยู่ปัจจุบัน กรุณาป้อนรหัสไปรษณีย์.
        /// </summary>
        public static string errorRegisGeneral_ucAddressCurrent_errorPostcodeAddressRequired {
            get {
                return ResourceManager.GetString("errorRegisGeneral_ucAddressCurrent_errorPostcodeAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่อยู่ปัจจุบัน กรุณาเลือกจังหวัด.
        /// </summary>
        public static string errorRegisGeneral_ucAddressCurrent_errorProvinceAddressRequired {
            get {
                return ResourceManager.GetString("errorRegisGeneral_ucAddressCurrent_errorProvinceAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่อยู่ตามทะเบียนบ้าน กรุณากรอกที่อยู่.
        /// </summary>
        public static string errorRegisGeneral_ucAddressRegister_errorAddressRequired {
            get {
                return ResourceManager.GetString("errorRegisGeneral_ucAddressRegister_errorAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่อยู่ตามทะเบียนบ้าน กรุณาเลือกอำเภอ.
        /// </summary>
        public static string errorRegisGeneral_ucAddressRegister_errorDistrictAddressRequired {
            get {
                return ResourceManager.GetString("errorRegisGeneral_ucAddressRegister_errorDistrictAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่อยู่ตามทะเบียนบ้าน กรุณาเลือกตำบล.
        /// </summary>
        public static string errorRegisGeneral_ucAddressRegister_errorParishAddressRequired {
            get {
                return ResourceManager.GetString("errorRegisGeneral_ucAddressRegister_errorParishAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่อยู่ตามทะเบียนบ้าน กรุณาป้อนรหัสไปรษณีย์.
        /// </summary>
        public static string errorRegisGeneral_ucAddressRegister_errorPostcodeAddressRequired {
            get {
                return ResourceManager.GetString("errorRegisGeneral_ucAddressRegister_errorPostcodeAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่อยู่ตามทะเบียนบ้าน กรุณาเลือกจังหวัด.
        /// </summary>
        public static string errorRegisGeneral_ucAddressRegister_errorProvinceAddressRequired {
            get {
                return ResourceManager.GetString("errorRegisGeneral_ucAddressRegister_errorProvinceAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกประเภทสมาชิกและสถานะ.
        /// </summary>
        public static string errorRegSearchOfficerOIC_001 {
            get {
                return ResourceManager.GetString("errorRegSearchOfficerOIC_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกสถานะ.
        /// </summary>
        public static string errorRegSearchOfficerOIC_002 {
            get {
                return ResourceManager.GetString("errorRegSearchOfficerOIC_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกประเภทสมาชิก.
        /// </summary>
        public static string errorRegSearchOfficerOIC_003 {
            get {
                return ResourceManager.GetString("errorRegSearchOfficerOIC_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกวันที่เริ่มต้น.
        /// </summary>
        public static string errorRegSearchOfficerOIC_004 {
            get {
                return ResourceManager.GetString("errorRegSearchOfficerOIC_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกวันที่สิ้นสุด.
        /// </summary>
        public static string errorRegSearchOfficerOIC_005 {
            get {
                return ResourceManager.GetString("errorRegSearchOfficerOIC_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบชื่อประเภทไฟล์.
        /// </summary>
        public static string errorResultVerify_001 {
            get {
                return ResourceManager.GetString("errorResultVerify_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาตั้งค่า.
        /// </summary>
        public static string errorSettingAttach_002 {
            get {
                return ResourceManager.GetString("errorSettingAttach_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกต้นสังกัด.
        /// </summary>
        public static string errorSingleApplicant_001 {
            get {
                return ResourceManager.GetString("errorSingleApplicant_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เงื่อนไขในการค้นหา (ปี) ผิด กรุณาระบุปี พ.ศ. จำนวน4หลัก.
        /// </summary>
        public static string errorSingleApplicant_002 {
            get {
                return ResourceManager.GetString("errorSingleApplicant_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถสร้างกำหนดการสอบย้อนหลัง.
        /// </summary>
        public static string errorSingleApplicant_003 {
            get {
                return ResourceManager.GetString("errorSingleApplicant_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถระบุ Area Code ปัจจุบันได้.
        /// </summary>
        public static string errorSysMessage_AreaCodeNull {
            get {
                return ResourceManager.GetString("errorSysMessage_AreaCodeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาแนบไฟล์.
        /// </summary>
        public static string errorSysMessage_CannotAttachFile {
            get {
                return ResourceManager.GetString("errorSysMessage_CannotAttachFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถลบได้ กรุณาตรวจสอบวันที่และจำนวนคนในรอบสอบ.
        /// </summary>
        public static string errorSysMessage_CannotDeleteExamTestingNo {
            get {
                return ResourceManager.GetString("errorSysMessage_CannotDeleteExamTestingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถแก้ไขได้ มีผู้สมัครในรอบสอบนี้แล้วหรือตรวจสอบวันที่สอบย้อนหลัง.
        /// </summary>
        public static string errorSysMessage_CannotEditExamTestingNo {
            get {
                return ResourceManager.GetString("errorSysMessage_CannotEditExamTestingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกประเภทใบอนุญาต.
        /// </summary>
        public static string errorSysMessage_CannotLicesetype {
            get {
                return ResourceManager.GetString("errorSysMessage_CannotLicesetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกประเภทขอรับใบอนุญาต.
        /// </summary>
        public static string errorSysMessage_CannotPettitiontype {
            get {
                return ResourceManager.GetString("errorSysMessage_CannotPettitiontype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกประเภทรายการขอรับใบอนุญาต.
        /// </summary>
        public static string errorSysMessage_CannotType {
            get {
                return ResourceManager.GetString("errorSysMessage_CannotType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุไฟล์.
        /// </summary>
        public static string errorSysMessage_CannotUploadFile {
            get {
                return ResourceManager.GetString("errorSysMessage_CannotUploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถโหลดไฟล์ได้ เนื่องจากประเภทไฟล์ไม่ถูกต้อง.
        /// </summary>
        public static string errorSysMessage_CannotWrongUploadFile {
            get {
                return ResourceManager.GetString("errorSysMessage_CannotWrongUploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาติ๊กข้อมูลการยอมรับ.
        /// </summary>
        public static string errorSysMessage_CheckCondition {
            get {
                return ResourceManager.GetString("errorSysMessage_CheckCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกข้อมูล.
        /// </summary>
        public static string errorSysMessage_ChooseData {
            get {
                return ResourceManager.GetString("errorSysMessage_ChooseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สร้างใบสั่งจ่ายกลุ่มไม่สำเร็จ.
        /// </summary>
        public static string errorSysMessage_CreatePaymentError {
            get {
                return ResourceManager.GetString("errorSysMessage_CreatePaymentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ท่านได้สร้างใบสั่งจ่ายกลุ่มเรียบร้อย.
        /// </summary>
        public static string errorSysMessage_CreatePaymentSuccess {
            get {
                return ResourceManager.GetString("errorSysMessage_CreatePaymentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รูปแบบวันที่ไม่ถูกต้อง กรุณากรอกใหม่.
        /// </summary>
        public static string errorSysMessage_DateErrorFormat {
            get {
                return ResourceManager.GetString("errorSysMessage_DateErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มีรายการตั้งค่าไปแล้ว.
        /// </summary>
        public static string errorSysMessage_DupConfigSettingDocument {
            get {
                return ResourceManager.GetString("errorSysMessage_DupConfigSettingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รูปแบบอีเมลไม่ถูกต้อง กรุณากรอกใหม่.
        /// </summary>
        public static string errorSysMessage_EmailErrorFormat {
            get {
                return ResourceManager.GetString("errorSysMessage_EmailErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขนาดข้อมูลใหญ่ ไม่สามารถส่งออกได้.
        /// </summary>
        public static string errorSysMessage_ExcelSizeError {
            get {
                return ResourceManager.GetString("errorSysMessage_ExcelSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถระบุค่าธรรมเนียม ตามประเภทคำร้องขอใบแทนใบอนุญาต.
        /// </summary>
        public static string errorSysMessage_FeeNull {
            get {
                return ResourceManager.GetString("errorSysMessage_FeeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาแนบเอกสาร.
        /// </summary>
        public static string errorSysMessage_FileRequire {
            get {
                return ResourceManager.GetString("errorSysMessage_FileRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาตรวจสอบข้อมูลใบอนุญาตก่อนทำรายการถัดไป.
        /// </summary>
        public static string errorSysMessage_LicenseNull {
            get {
                return ResourceManager.GetString("errorSysMessage_LicenseNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบข้อมูลใบอนุญาตที่ผ่านการอนุมัติ.
        /// </summary>
        public static string errorSysMessage_LicenseYNotFound {
            get {
                return ResourceManager.GetString("errorSysMessage_LicenseYNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่มีข้อมูลในระบบ.
        /// </summary>
        public static string errorSysMessage_NoData {
            get {
                return ResourceManager.GetString("errorSysMessage_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสผ่านไม่ตรงกัน.
        /// </summary>
        public static string errorSysMessage_NotSame {
            get {
                return ResourceManager.GetString("errorSysMessage_NotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสผ่านใหม่ห้ามตรงกับรหัสผ่านเก่า.
        /// </summary>
        public static string errorSysMessage_PleaseChangeDefault {
            get {
                return ResourceManager.GetString("errorSysMessage_PleaseChangeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกข้อมูลบริษัทให้ถูกต้อง.
        /// </summary>
        public static string errorSysMessage_PleaseInputCompany {
            get {
                return ResourceManager.GetString("errorSysMessage_PleaseInputCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกหมายเลขบริษัท.
        /// </summary>
        public static string errorSysMessage_PleaseInputCompCode {
            get {
                return ResourceManager.GetString("errorSysMessage_PleaseInputCompCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกรหัสสอบให้ถูกต้อง.
        /// </summary>
        public static string errorSysMessage_PleaseInputTestingNo {
            get {
                return ResourceManager.GetString("errorSysMessage_PleaseInputTestingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกรหัสผ่านใหม่ให้ตรงกับยืนยันรหัสผ่าน.
        /// </summary>
        public static string errorSysMessage_PleaseSamePassword {
            get {
                return ResourceManager.GetString("errorSysMessage_PleaseSamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกธนาคาร.
        /// </summary>
        public static string errorSysMessage_PleaseSelectBankData {
            get {
                return ResourceManager.GetString("errorSysMessage_PleaseSelectBankData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกวัน.
        /// </summary>
        public static string errorSysMessage_PleaseSelectDate {
            get {
                return ResourceManager.GetString("errorSysMessage_PleaseSelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกไฟล์.
        /// </summary>
        public static string errorSysMessage_PleaseSelectFileData {
            get {
                return ResourceManager.GetString("errorSysMessage_PleaseSelectFileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกไฟล์นามสกุล .txt ให้ถูกต้อง.
        /// </summary>
        public static string errorSysMessage_PleaseSelectFileTxt {
            get {
                return ResourceManager.GetString("errorSysMessage_PleaseSelectFileTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โปรดตรวจสอบวันเดือนปีเกิดให้ถูกต้องอีกครั้ง.
        /// </summary>
        public static string errorSysMessage_RegBirthDayValidationF {
            get {
                return ResourceManager.GetString("errorSysMessage_RegBirthDayValidationF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสผ่านไม่ตรงกัน.
        /// </summary>
        public static string errorSysMessage_RegValidationCompare {
            get {
                return ResourceManager.GetString("errorSysMessage_RegValidationCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณายืนยันรหัสผ่าน.
        /// </summary>
        public static string errorSysMessage_RegValidationConfirmPass {
            get {
                return ResourceManager.GetString("errorSysMessage_RegValidationConfirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสผ่านต้องมีความยาวอย่างน้อย 8 ตัวอักษร แต่ไม่เกิน 14 ตัวอักษร&lt;br/&gt;รหัสผ่านต้องผสมระหว่างตัวเลข ตัวอักษรพิมพ์ใหญ่ ตัวอักษรพิมพ์เล็ก และอักขระพิเศษ อย่างละ 1 ตัวขึ้นไป&lt;br/&gt;อักขระที่อนุญาตให้กำหนดรหัสผ่านได้คือ 0-9 A-Z a-z @ # $ % ^ &amp; _ ( ) { } + ? และ , เท่านั้น.
        /// </summary>
        public static string errorSysMessage_RegValidationPW {
            get {
                return ResourceManager.GetString("errorSysMessage_RegValidationPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบข้อมูลใบอนุญาต.
        /// </summary>
        public static string errorSysMessage_RenewLicenseNotFound {
            get {
                return ResourceManager.GetString("errorSysMessage_RenewLicenseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุรหัสผ่าน.
        /// </summary>
        public static string errorSysMessage_ReqValidationPW {
            get {
                return ResourceManager.GetString("errorSysMessage_ReqValidationPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เกิดข้อผิดพลาดจาก Server.
        /// </summary>
        public static string errorSysMessage_ServerError {
            get {
                return ResourceManager.GetString("errorSysMessage_ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่ผ่าน.
        /// </summary>
        public static string errorSysMessage_TrainResultF {
            get {
                return ResourceManager.GetString("errorSysMessage_TrainResultF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาตรวจสอบข้อมูลใหม่.
        /// </summary>
        public static string errorSysMessage_TryAgain {
            get {
                return ResourceManager.GetString("errorSysMessage_TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลผู้ไม่ตรงกับในระบบ.
        /// </summary>
        public static string errorSysMessage_UserMissMatchRegitrationData {
            get {
                return ResourceManager.GetString("errorSysMessage_UserMissMatchRegitrationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถระบุผู้ใช้งานปัจจุบัน.
        /// </summary>
        public static string errorSysMessage_UserRequire {
            get {
                return ResourceManager.GetString("errorSysMessage_UserRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: .
        /// </summary>
        public static string errortestImg_001 {
            get {
                return ResourceManager.GetString("errortestImg_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสบัตรประชาชนไม่ถูกต้อง.
        /// </summary>
        public static string errorTestUploadData_001 {
            get {
                return ResourceManager.GetString("errorTestUploadData_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณเลือกไฟล์ซ้ำ !!! .
        /// </summary>
        public static string errorTestUploadData_002 {
            get {
                return ResourceManager.GetString("errorTestUploadData_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบข้อมูลของเลขบัตรประชาชน .
        /// </summary>
        public static string errorucLicenseDetail_001 {
            get {
                return ResourceManager.GetString("errorucLicenseDetail_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกรายการต้องการอนุมัติ.
        /// </summary>
        public static string errorVerifydoc_001 {
            get {
                return ResourceManager.GetString("errorVerifydoc_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มีปัญหาการระบุข้อมูลของไฟล์TestZip_ขอรับใบอนุญาต.zipไม่ได้ระบุเลขที่ใบอนุญาต ไม่ได้ระบุวันที่ออกใบอนุญาตปัจจุบัน ไม่ได้ระบุวันที่หมดอายุใบอนุญาตปัจจุบัน ระบุค่าธรรมเนียมในการต่ออายุ1ปีน้อยกว่า200บาท ไม่พบใบอนุญาตที่ระบุ.
        /// </summary>
        public static string errorWebForm6_001 {
            get {
                return ResourceManager.GetString("errorWebForm6_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error .
        /// </summary>
        public static string errorwebTestUpload_001 {
            get {
                return ResourceManager.GetString("errorwebTestUpload_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success....
        /// </summary>
        public static string errorwebTestUpload_002 {
            get {
                return ResourceManager.GetString("errorwebTestUpload_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string errorwebTestUpload_003 {
            get {
                return ResourceManager.GetString("errorwebTestUpload_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิกการสมัครสอบเรียบร้อยแล้ว.
        /// </summary>
        public static string infoApplicantDetail_001 {
            get {
                return ResourceManager.GetString("infoApplicantDetail_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชำระเงินล่าช้า.
        /// </summary>
        public static string infoApplicantDetail_003 {
            get {
                return ResourceManager.GetString("infoApplicantDetail_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยังไม่ได้ชำระเงิน.
        /// </summary>
        public static string infoApplicantDetail_004 {
            get {
                return ResourceManager.GetString("infoApplicantDetail_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รอผลสอบ.
        /// </summary>
        public static string infoApplicantDetail_DetailTotalExam {
            get {
                return ResourceManager.GetString("infoApplicantDetail_DetailTotalExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิกรายการ .
        /// </summary>
        public static string infoApplicantNoPay_001 {
            get {
                return ResourceManager.GetString("infoApplicantNoPay_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  รายการเรียบร้อยแล้ว.
        /// </summary>
        public static string infoApplicantNoPay_002 {
            get {
                return ResourceManager.GetString("infoApplicantNoPay_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่มีข้อมูล.
        /// </summary>
        public static string infoBarcodes_001 {
            get {
                return ResourceManager.GetString("infoBarcodes_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขาดสอบ.
        /// </summary>
        public static string infoExamResult_001 {
            get {
                return ResourceManager.GetString("infoExamResult_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่ผ่าน.
        /// </summary>
        public static string infoExamResult_002 {
            get {
                return ResourceManager.GetString("infoExamResult_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผ่าน.
        /// </summary>
        public static string infoExamResult_003 {
            get {
                return ResourceManager.GetString("infoExamResult_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผลการสอบผิดพลาด.
        /// </summary>
        public static string infoExamResult_004 {
            get {
                return ResourceManager.GetString("infoExamResult_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สร้างใบเสร็จสำเร็จ.
        /// </summary>
        public static string infoGenPayment_001 {
            get {
                return ResourceManager.GetString("infoGenPayment_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นำเข้าข้อมูลการสมัครสอบแบบกลุ่ม เรียบร้อยแล้ว.
        /// </summary>
        public static string infoGroupApplicantDetail_001 {
            get {
                return ResourceManager.GetString("infoGroupApplicantDetail_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download completed!.
        /// </summary>
        public static string infoGroupApplicantDetail_002 {
            get {
                return ResourceManager.GetString("infoGroupApplicantDetail_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username หรือ Password ไม่ถูกต้อง.
        /// </summary>
        public static string infohome_001 {
            get {
                return ResourceManager.GetString("infohome_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บันทึกสำเร็จ.
        /// </summary>
        public static string infoInvoice_001 {
            get {
                return ResourceManager.GetString("infoInvoice_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ท่านได้สร้างใบอนุญาตเรียบร้อยแล้ว.
        /// </summary>
        public static string infoLicenseApprove_001 {
            get {
                return ResourceManager.GetString("infoLicenseApprove_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อผู้ใช้งานของท่านคือเลขบัตรประชาชน.
        /// </summary>
        public static string infoMasterRegister_001 {
            get {
                return ResourceManager.GetString("infoMasterRegister_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุรหัสผ่านของท่านเพื่อเป็นการยืนยันการสมัคร.
        /// </summary>
        public static string infoMasterRegister_002 {
            get {
                return ResourceManager.GetString("infoMasterRegister_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อผู้ใช้งานของท่านคืออีเมลที่ใช้ในการสมัครสมาชิก.
        /// </summary>
        public static string infoMasterRegister_003 {
            get {
                return ResourceManager.GetString("infoMasterRegister_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทำการบันทึกข้อมูลเรียบร้อย รอการอนุมัติการแก้ไขภายหลัง.
        /// </summary>
        public static string infoReg_Assoc_001 {
            get {
                return ResourceManager.GetString("infoReg_Assoc_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ท่านยังไม่ได้ ยอมรับเงื่อนไขการสมัคร.
        /// </summary>
        public static string inforegExplain_001 {
            get {
                return ResourceManager.GetString("inforegExplain_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกรายการ.
        /// </summary>
        public static string infoRegSearchOfficerOIC_006 {
            get {
                return ResourceManager.GetString("infoRegSearchOfficerOIC_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ท่านได้ทำการอนุมัติกลุ่มเรียบร้อยแล้ว.
        /// </summary>
        public static string infoRegSearchOfficerOIC_007 {
            get {
                return ResourceManager.GetString("infoRegSearchOfficerOIC_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (หากเวลากำหนดเข้าห้องสอบผ่านไปแล้ว 15 นาที ผู้สมัครสอบไม่มีสิทธิเข้าห้องสอบ).
        /// </summary>
        public static string infoRptBillPayment_ExamRemark {
            get {
                return ResourceManager.GetString("infoRptBillPayment_ExamRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บันทึกข้อมูลเรียบร้อย.
        /// </summary>
        public static string infoSetHoliday_001 {
            get {
                return ResourceManager.GetString("infoSetHoliday_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลบข้อมูลเรียบร้อย.
        /// </summary>
        public static string infoSetHoliday_002 {
            get {
                return ResourceManager.GetString("infoSetHoliday_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แก้ไขข้อมูลเรียบร้อย.
        /// </summary>
        public static string infoSetHoliday_003 {
            get {
                return ResourceManager.GetString("infoSetHoliday_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บันทึกข้อมูลสำเร็จ.
        /// </summary>
        public static string infoSetSubject_001 {
            get {
                return ResourceManager.GetString("infoSetSubject_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แก้ไขข้อมูลสำเร็จ.
        /// </summary>
        public static string infoSetSubject_002 {
            get {
                return ResourceManager.GetString("infoSetSubject_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลบข้อมูลสำเร็จ.
        /// </summary>
        public static string infoSetSubject_003 {
            get {
                return ResourceManager.GetString("infoSetSubject_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณต้องการลบข้อมูลหรือไม่?.
        /// </summary>
        public static string infoSettingAttach_001 {
            get {
                return ResourceManager.GetString("infoSettingAttach_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณายืนยันเงื่อนไขก่อนทำรายการถัดไป.
        /// </summary>
        public static string infoSysMessage_AgreementRequire {
            get {
                return ResourceManager.GetString("infoSysMessage_AgreementRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อนุมัติเรียบร้อย.
        /// </summary>
        public static string infoSysMessage_Approval {
            get {
                return ResourceManager.GetString("infoSysMessage_Approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไปแล้ว หากไม่ถูกต้องโปรดยกเลิกโดยการกดเครื่องหมาย กากบาท แล้วค่อยดำเนินการบันทึกใหม่.
        /// </summary>
        public static string infoSysMessage_AttachFileDupEnt {
            get {
                return ResourceManager.GetString("infoSysMessage_AttachFileDupEnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ท่านได้บันทึก... ไว้ก่อนหน้านี้แล้ว หากไม่ถูกต้องโปรดยกเลิกโดยการกดเครื่องหมาย กากบาท แล้วค่อยดำเนินการบันทึกใหม่.
        /// </summary>
        public static string infoSysMessage_AttachFileDupicate {
            get {
                return ResourceManager.GetString("infoSysMessage_AttachFileDupicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ท่านได้แนบไฟล์.
        /// </summary>
        public static string infoSysMessage_AttachFileDupstart {
            get {
                return ResourceManager.GetString("infoSysMessage_AttachFileDupstart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การอัพโหลดไฟล์ ต้องมีขนาดไม่เกิน 1 MB..
        /// </summary>
        public static string infoSysMessage_AttachNotOverOneMB {
            get {
                return ResourceManager.GetString("infoSysMessage_AttachNotOverOneMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระบบได้จัดส่งรหัสผ่านให้ท่านเรียบร้อยแล้ว โปรดตรวจสอบอีเมลเพื่อทำการยืนยันรหัสผ่านใหม่.
        /// </summary>
        public static string infoSysMessage_ConfirmChangePasswordMail {
            get {
                return ResourceManager.GetString("infoSysMessage_ConfirmChangePasswordMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Data Empty : .
        /// </summary>
        public static string infoSysMessage_DataEmpty {
            get {
                return ResourceManager.GetString("infoSysMessage_DataEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทั้งหมด.
        /// </summary>
        public static string infoSysMessage_DefaultAll {
            get {
                return ResourceManager.GetString("infoSysMessage_DefaultAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือก.
        /// </summary>
        public static string infoSysMessage_DefaultSelecting {
            get {
                return ResourceManager.GetString("infoSysMessage_DefaultSelecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลบการตั้งค่าเรียบร้อย.
        /// </summary>
        public static string infoSysMessage_DeleteConfigLicense {
            get {
                return ResourceManager.GetString("infoSysMessage_DeleteConfigLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete File.
        /// </summary>
        public static string infoSysMessage_DeleteFile {
            get {
                return ResourceManager.GetString("infoSysMessage_DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลบรายการแล้ว.
        /// </summary>
        public static string infoSysMessage_DeleteSuccess {
            get {
                return ResourceManager.GetString("infoSysMessage_DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ท่านได้เคยทำการลงทะเบียนสมาชิกไว้แล้วกรุณากลับไปหน้าแรกเพื่อทำการ Login.
        /// </summary>
        public static string infoSysMessage_DialogLoginFail {
            get {
                return ResourceManager.GetString("infoSysMessage_DialogLoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลงทะเบียน.
        /// </summary>
        public static string infoSysMessage_DialogLoginTitle {
            get {
                return ResourceManager.GetString("infoSysMessage_DialogLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทำการบันทึกข้อมูลเรียบร้อย รอการอนุมัติการสมัครภายหลัง.
        /// </summary>
        public static string infoSysMessage_EditSuccess {
            get {
                return ResourceManager.GetString("infoSysMessage_EditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทำการบันทึกข้อมูลเรียบร้อย.
        /// </summary>
        public static string infoSysMessage_EditSuccess2 {
            get {
                return ResourceManager.GetString("infoSysMessage_EditSuccess2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่ผ่าน.
        /// </summary>
        public static string infoSysMessage_ExamResultF {
            get {
                return ResourceManager.GetString("infoSysMessage_ExamResultF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขาดสอบ.
        /// </summary>
        public static string infoSysMessage_ExamResultM {
            get {
                return ResourceManager.GetString("infoSysMessage_ExamResultM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่มีผลสอบ.
        /// </summary>
        public static string infoSysMessage_ExamResultN {
            get {
                return ResourceManager.GetString("infoSysMessage_ExamResultN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผ่าน.
        /// </summary>
        public static string infoSysMessage_ExamResultP {
            get {
                return ResourceManager.GetString("infoSysMessage_ExamResultP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผิดพลาด.
        /// </summary>
        public static string infoSysMessage_Fail {
            get {
                return ResourceManager.GetString("infoSysMessage_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มรายการแล้ว.
        /// </summary>
        public static string infoSysMessage_InsertSuccess {
            get {
                return ResourceManager.GetString("infoSysMessage_InsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่อนุมัติเรียบร้อย.
        /// </summary>
        public static string infoSysMessage_NotApproval {
            get {
                return ResourceManager.GetString("infoSysMessage_NotApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทไฟล์ไม่ถูกต้อง.
        /// </summary>
        public static string infoSysMessage_NotTypeFile {
            get {
                return ResourceManager.GetString("infoSysMessage_NotTypeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกประเภทสมาชิก OIC.
        /// </summary>
        public static string infoSysMessage_PleaseChooesTypeMemberOIC {
            get {
                return ResourceManager.GetString("infoSysMessage_PleaseChooesTypeMemberOIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกประเภทไฟล์ให้ถูกต้อง.
        /// </summary>
        public static string infoSysMessage_PleaseChooseFile {
            get {
                return ResourceManager.GetString("infoSysMessage_PleaseChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ท่านยังไม่ได้เลิกประเภทการลงทะเบียน.
        /// </summary>
        public static string infoSysMessage_PleaseChooseMemberType {
            get {
                return ResourceManager.GetString("infoSysMessage_PleaseChooseMemberType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาลบไฟล์เก่าก่อน ที่จะ Upload ใหม่.
        /// </summary>
        public static string infoSysMessage_PleaseDeleteFile {
            get {
                return ResourceManager.GetString("infoSysMessage_PleaseDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกข้อมูลให้ครบ.
        /// </summary>
        public static string infoSysMessage_PleaseInputFill {
            get {
                return ResourceManager.GetString("infoSysMessage_PleaseInputFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกข้อมูลบัตรประชาชน.
        /// </summary>
        public static string infoSysMessage_PleaseInputIDNumber {
            get {
                return ResourceManager.GetString("infoSysMessage_PleaseInputIDNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทั้งหมด.
        /// </summary>
        public static string infoSysMessage_PleaseSelectAll {
            get {
                return ResourceManager.GetString("infoSysMessage_PleaseSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกไฟล์นามสกุลให้ถูกต้อง.
        /// </summary>
        public static string infoSysMessage_PleaseSelectFile {
            get {
                return ResourceManager.GetString("infoSysMessage_PleaseSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทำการบันทึกข้อมูลเรียบร้อย รอการอนุมัติการสมัครภายหลัง.
        /// </summary>
        public static string infoSysMessage_RegisSuccess {
            get {
                return ResourceManager.GetString("infoSysMessage_RegisSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทำการบันทึกข้อมูลเรียบร้อย.
        /// </summary>
        public static string infoSysMessage_RegisSuccess2 {
            get {
                return ResourceManager.GetString("infoSysMessage_RegisSuccess2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สมัครสมาชิกเรียบร้อยแล้วขอบคุณค่ะ.
        /// </summary>
        public static string infoSysMessage_SaveAssociationSuccess {
            get {
                return ResourceManager.GetString("infoSysMessage_SaveAssociationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทำการบันทึกข้อมูลเรียบร้อย.
        /// </summary>
        public static string infoSysMessage_SaveSucess {
            get {
                return ResourceManager.GetString("infoSysMessage_SaveSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        public static string infoSysMessage_SelectFile {
            get {
                return ResourceManager.GetString("infoSysMessage_SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตั้งค่าเรียบร้อย.
        /// </summary>
        public static string infoSysMessage_SuccessConfigLicense {
            get {
                return ResourceManager.GetString("infoSysMessage_SuccessConfigLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลบการสร้างกำหนดการสอบ.
        /// </summary>
        public static string infoSysMessage_SuccessDeleteExam {
            get {
                return ResourceManager.GetString("infoSysMessage_SuccessDeleteExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แก้ไขข้อมูลเจ้าหน้าที่ คปภ. เรียบร้อยแล้ว.
        /// </summary>
        public static string infoSysMessage_SuccessEditTypeOIC {
            get {
                return ResourceManager.GetString("infoSysMessage_SuccessEditTypeOIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นำเข้าระบบเรียบร้อย.
        /// </summary>
        public static string infoSysMessage_SuccessImportData {
            get {
                return ResourceManager.GetString("infoSysMessage_SuccessImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มการสมัครเรียบร้อย.
        /// </summary>
        public static string infoSysMessage_SuccessInsertApplicant {
            get {
                return ResourceManager.GetString("infoSysMessage_SuccessInsertApplicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มการขอใบอนุญาตเรียบร้อย.
        /// </summary>
        public static string infoSysMessage_SuccessInsertLicenseSingle {
            get {
                return ResourceManager.GetString("infoSysMessage_SuccessInsertLicenseSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มการลงทะเบียนเจ้าหน้าที่กลุ่มสนามสอบ.
        /// </summary>
        public static string infoSysMessage_SuccessInsertTypeGroupPlace {
            get {
                return ResourceManager.GetString("infoSysMessage_SuccessInsertTypeGroupPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มการลงทะเบียนเจ้าหน้าที่ คปภ..
        /// </summary>
        public static string infoSysMessage_SuccessInsertTypeOIC {
            get {
                return ResourceManager.GetString("infoSysMessage_SuccessInsertTypeOIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มสมาชิก.
        /// </summary>
        public static string infoSysMessage_TitleTypeMemberOIC {
            get {
                return ResourceManager.GetString("infoSysMessage_TitleTypeMemberOIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผ่าน.
        /// </summary>
        public static string infoSysMessage_TrainResultP {
            get {
                return ResourceManager.GetString("infoSysMessage_TrainResultP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิกการสมัครสอบ.
        /// </summary>
        public static string propApplicantDetail_001 {
            get {
                return ResourceManager.GetString("propApplicantDetail_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชำระเงินแล้ว.
        /// </summary>
        public static string propApplicantDetail_002 {
            get {
                return ResourceManager.GetString("propApplicantDetail_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ::ข้อมูลในเลขที่ใบสั่งจ่ายกลุ่ม .
        /// </summary>
        public static string propApplicantNoPay_group_request {
            get {
                return ResourceManager.GetString("propApplicantNoPay_group_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เบอร์โทรศัพท์.
        /// </summary>
        public static string propEdit_Reg_Person_001 {
            get {
                return ResourceManager.GetString("propEdit_Reg_Person_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เบอร์โทรศัพท์มือถือ.
        /// </summary>
        public static string propEdit_Reg_Person_002 {
            get {
                return ResourceManager.GetString("propEdit_Reg_Person_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เบอร์โทรศัพท์หน่วยงาน.
        /// </summary>
        public static string propEdit_Reg_Person_003 {
            get {
                return ResourceManager.GetString("propEdit_Reg_Person_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขที่ใบสั่งจ่ายย่อย .
        /// </summary>
        public static string propGenPayment_001 {
            get {
                return ResourceManager.GetString("propGenPayment_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขที่ใบสั่งจ่ายกลุ่ม .
        /// </summary>
        public static string propGenPayment_group_request {
            get {
                return ResourceManager.GetString("propGenPayment_group_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถนำเข้าข้อมูล เนื่องจากข้อมูลไม่ถูกต้อง.
        /// </summary>
        public static string propGroupApplicantDetail_ErrMessage {
            get {
                return ResourceManager.GetString("propGroupApplicantDetail_ErrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายการใบอนุญาตทั้งหมด.
        /// </summary>
        public static string propLicenseCheck_LicensePaymentAll {
            get {
                return ResourceManager.GetString("propLicenseCheck_LicensePaymentAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายการใบอนุญาตที่ผ่านการอนุมัติ.
        /// </summary>
        public static string propLicenseCheck_LicensePaymentY {
            get {
                return ResourceManager.GetString("propLicenseCheck_LicensePaymentY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หญิง.
        /// </summary>
        public static string propLicenseGroup_Female {
            get {
                return ResourceManager.GetString("propLicenseGroup_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชาย.
        /// </summary>
        public static string propLicenseGroup_Male {
            get {
                return ResourceManager.GetString("propLicenseGroup_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตัวแทนประกันชีวิต.
        /// </summary>
        public static string propLicenseService_032 {
            get {
                return ResourceManager.GetString("propLicenseService_032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตัวแทนประกันวินาศภัย.
        /// </summary>
        public static string propLicenseService_033 {
            get {
                return ResourceManager.GetString("propLicenseService_033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การจัดการประกันชีวิตโดยตรง.
        /// </summary>
        public static string propLicenseService_034 {
            get {
                return ResourceManager.GetString("propLicenseService_034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การจัดการประกันวินาศภัยโดยตรง.
        /// </summary>
        public static string propLicenseService_035 {
            get {
                return ResourceManager.GetString("propLicenseService_035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การประกันภัยอุบัติเหตุส่วนบุคคลและประกันสุขภาพ.
        /// </summary>
        public static string propLicenseService_036 {
            get {
                return ResourceManager.GetString("propLicenseService_036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พรบ.คุ้มครองผู้ประสบภัยจากรถ.
        /// </summary>
        public static string propLicenseService_037 {
            get {
                return ResourceManager.GetString("propLicenseService_037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สำหรับการประกันภัยรายย่อย(ชีวิต).
        /// </summary>
        public static string propLicenseService_038 {
            get {
                return ResourceManager.GetString("propLicenseService_038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สำหรับการประกันภัยรายย่อย(วินาศภัย).
        /// </summary>
        public static string propLicenseService_039 {
            get {
                return ResourceManager.GetString("propLicenseService_039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string propLicenseService_040 {
            get {
                return ResourceManager.GetString("propLicenseService_040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขอใบอนุญาตใหม่.
        /// </summary>
        public static string propLicenseService_041 {
            get {
                return ResourceManager.GetString("propLicenseService_041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขอต่ออายุใบอนุญาต 1 ปี.
        /// </summary>
        public static string propLicenseService_042 {
            get {
                return ResourceManager.GetString("propLicenseService_042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขอต่ออายุใบอนุญาต 5 ปี.
        /// </summary>
        public static string propLicenseService_043 {
            get {
                return ResourceManager.GetString("propLicenseService_043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขาดต่อขอใหม่.
        /// </summary>
        public static string propLicenseService_044 {
            get {
                return ResourceManager.GetString("propLicenseService_044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใบแทนใบอนุญาต(ชำรุดสูญหาย).
        /// </summary>
        public static string propLicenseService_045 {
            get {
                return ResourceManager.GetString("propLicenseService_045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รออนุมัติ.
        /// </summary>
        public static string propLicenseService_046 {
            get {
                return ResourceManager.GetString("propLicenseService_046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่อนุมัติ.
        /// </summary>
        public static string propLicenseService_047 {
            get {
                return ResourceManager.GetString("propLicenseService_047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อนุมัติ.
        /// </summary>
        public static string propLicenseService_048 {
            get {
                return ResourceManager.GetString("propLicenseService_048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่มีผลสอบ.
        /// </summary>
        public static string propLicenseValidate_ResExam {
            get {
                return ResourceManager.GetString("propLicenseValidate_ResExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่มีผลอบรม.
        /// </summary>
        public static string propLicenseValidate_ResTrain {
            get {
                return ResourceManager.GetString("propLicenseValidate_ResTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขอรับใบอนุญาตใหม่.
        /// </summary>
        public static string propMasterLicense_001 {
            get {
                return ResourceManager.GetString("propMasterLicense_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขอต่ออายุใบอนุญาต.
        /// </summary>
        public static string propMasterLicense_002 {
            get {
                return ResourceManager.GetString("propMasterLicense_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใบแทนใบอนุญาต(ชำรุดสูญหาย).
        /// </summary>
        public static string propMasterLicense_003 {
            get {
                return ResourceManager.GetString("propMasterLicense_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตรวจสอบการอนุมัติเอกสาร.
        /// </summary>
        public static string propMasterLicense_004 {
            get {
                return ResourceManager.GetString("propMasterLicense_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การลงทะเบียนแก้ไขอยู่ในระหว่างการพิจารณาของเจ้าหน้าที่.
        /// </summary>
        public static string propMasterPerson_001 {
            get {
                return ResourceManager.GetString("propMasterPerson_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตัวแทนประกันชีวิต.
        /// </summary>
        public static string propNatta_License001 {
            get {
                return ResourceManager.GetString("propNatta_License001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตัวแทนประกันวินาศภัย.
        /// </summary>
        public static string propNatta_License002 {
            get {
                return ResourceManager.GetString("propNatta_License002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การจัดการประกันชีวิตโดยตรง.
        /// </summary>
        public static string propNatta_License003 {
            get {
                return ResourceManager.GetString("propNatta_License003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การจัดการประกันวินาศภัยโดยตรง.
        /// </summary>
        public static string propNatta_License004 {
            get {
                return ResourceManager.GetString("propNatta_License004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การประกันภัยอุบัติเหตุส่วนบุคคลและประกันสุขภาพ.
        /// </summary>
        public static string propNatta_License005 {
            get {
                return ResourceManager.GetString("propNatta_License005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พรบ.คุ้มครองผู้ประสบภัยจากรถ.
        /// </summary>
        public static string propNatta_License006 {
            get {
                return ResourceManager.GetString("propNatta_License006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สำหรับการประกันภัยรายย่อย(ชีวิต).
        /// </summary>
        public static string propNatta_License007 {
            get {
                return ResourceManager.GetString("propNatta_License007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สำหรับการประกันภัยรายย่อย(วินาศภัย).
        /// </summary>
        public static string propNatta_License008 {
            get {
                return ResourceManager.GetString("propNatta_License008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string propNatta_License009 {
            get {
                return ResourceManager.GetString("propNatta_License009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใหม่.
        /// </summary>
        public static string propNatta_Pettion001 {
            get {
                return ResourceManager.GetString("propNatta_Pettion001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขอต่ออายุใบอนุญาต 1 ปี.
        /// </summary>
        public static string propNatta_Pettion002 {
            get {
                return ResourceManager.GetString("propNatta_Pettion002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขอต่ออายุใบอนุญาต 5 ปี.
        /// </summary>
        public static string propNatta_Pettion003 {
            get {
                return ResourceManager.GetString("propNatta_Pettion003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขาดต่อขอใหม่.
        /// </summary>
        public static string propNatta_Pettion004 {
            get {
                return ResourceManager.GetString("propNatta_Pettion004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค่าสมัครสอบ.
        /// </summary>
        public static string propPaymentDetail_TypePay {
            get {
                return ResourceManager.GetString("propPaymentDetail_TypePay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แก้ไขข้อมูล (สมาคม).
        /// </summary>
        public static string propPersonAssociate_001 {
            get {
                return ResourceManager.GetString("propPersonAssociate_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูล (สมาคม).
        /// </summary>
        public static string propPersonAssociate_002 {
            get {
                return ResourceManager.GetString("propPersonAssociate_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การลงทะเบียนแก้ไขไม่ผ่านการอนุมัติจากเจ้าหน้าที่.
        /// </summary>
        public static string propPersonAssociate_notApprove {
            get {
                return ResourceManager.GetString("propPersonAssociate_notApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แก้ไขข้อมูล (บริษัท).
        /// </summary>
        public static string propPersonCompany_001 {
            get {
                return ResourceManager.GetString("propPersonCompany_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูล (บริษัท).
        /// </summary>
        public static string propPersonCompany_002 {
            get {
                return ResourceManager.GetString("propPersonCompany_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แก้ไขข้อมูลผู้ใช้ระบบ.
        /// </summary>
        public static string propPersonGeneral_001 {
            get {
                return ResourceManager.GetString("propPersonGeneral_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลผู้ใช้ระบบ.
        /// </summary>
        public static string propPersonGeneral_002 {
            get {
                return ResourceManager.GetString("propPersonGeneral_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สมาคม.
        /// </summary>
        public static string propReg_Assoc_MemberTypeAssoc {
            get {
                return ResourceManager.GetString("propReg_Assoc_MemberTypeAssoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บริษัท.
        /// </summary>
        public static string propReg_Co_MemberTypeCompany {
            get {
                return ResourceManager.GetString("propReg_Co_MemberTypeCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บุคคลทั่วไป/ตัวแทน/นายหน้า.
        /// </summary>
        public static string propReg_NotApprove_MemberTypeGeneral {
            get {
                return ResourceManager.GetString("propReg_NotApprove_MemberTypeGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การลงทะเบียนไม่ผ่านการอนุมัติจากเจ้าหน้าที่.
        /// </summary>
        public static string propReg_NotApprove_notApprove {
            get {
                return ResourceManager.GetString("propReg_NotApprove_notApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssociationValidationGroup.
        /// </summary>
        public static string propReg_NotApprove_reqRegAssoc {
            get {
                return ResourceManager.GetString("propReg_NotApprove_reqRegAssoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การลงทะเบียนอยู่ในระหว่างการพิจารณาของเจ้าหน้าที่.
        /// </summary>
        public static string propReg_NotApprove_waitApprove {
            get {
                return ResourceManager.GetString("propReg_NotApprove_waitApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เจ้าหน้าที่กลุ่มสนามสอบ.
        /// </summary>
        public static string propReg_Place_Group_001 {
            get {
                return ResourceManager.GetString("propReg_Place_Group_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แก้ไขข้อมูล (เจ้าหน้าที่กลุ่มสนามสอบ).
        /// </summary>
        public static string propReg_Place_Group_002 {
            get {
                return ResourceManager.GetString("propReg_Place_Group_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูล (เจ้าหน้าที่กลุ่มสนามสอบ).
        /// </summary>
        public static string propReg_Place_Group_003 {
            get {
                return ResourceManager.GetString("propReg_Place_Group_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ::ข้อมูลบริษัท.
        /// </summary>
        public static string propregApproveCompany_001 {
            get {
                return ResourceManager.GetString("propregApproveCompany_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ::ข้อมูลพนักงานบริษัท.
        /// </summary>
        public static string propregApproveCompany_002 {
            get {
                return ResourceManager.GetString("propregApproveCompany_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทะเบียนบริษัท :.
        /// </summary>
        public static string propregApproveCompany_003 {
            get {
                return ResourceManager.GetString("propregApproveCompany_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ::ข้อมูลสมาคม.
        /// </summary>
        public static string propregApproveCompany_004 {
            get {
                return ResourceManager.GetString("propregApproveCompany_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ::ข้อมูลพนักงานสมาคม.
        /// </summary>
        public static string propregApproveCompany_005 {
            get {
                return ResourceManager.GetString("propregApproveCompany_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทะเบียนสมาคม :.
        /// </summary>
        public static string propregApproveCompany_006 {
            get {
                return ResourceManager.GetString("propregApproveCompany_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เบอร์โทรศัพท์บุคคล.
        /// </summary>
        public static string propregApproveOfficerOIC_001 {
            get {
                return ResourceManager.GetString("propregApproveOfficerOIC_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string propregApproveOfficerOIC_002 {
            get {
                return ResourceManager.GetString("propregApproveOfficerOIC_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyValidationGroup.
        /// </summary>
        public static string propRegisCompany_reqRegCompany {
            get {
                return ResourceManager.GetString("propRegisCompany_reqRegCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to regGuestValidationGroup.
        /// </summary>
        public static string propRegisGeneral_regGuest {
            get {
                return ResourceManager.GetString("propRegisGeneral_regGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รอพิจารณา.
        /// </summary>
        public static string propRequestVerifydoc_status {
            get {
                return ResourceManager.GetString("propRequestVerifydoc_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บาท.
        /// </summary>
        public static string propRptBillPayment_001 {
            get {
                return ResourceManager.GetString("propRptBillPayment_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สตางค์.
        /// </summary>
        public static string propRptBillPayment_002 {
            get {
                return ResourceManager.GetString("propRptBillPayment_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บาทถ้วน.
        /// </summary>
        public static string propRptBillPayment_003 {
            get {
                return ResourceManager.GetString("propRptBillPayment_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่สอบ.
        /// </summary>
        public static string propRptBillPayment_HeadapplyDate {
            get {
                return ResourceManager.GetString("propRptBillPayment_HeadapplyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานที่สอบ.
        /// </summary>
        public static string propRptBillPayment_HeadExamPlace {
            get {
                return ResourceManager.GetString("propRptBillPayment_HeadExamPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เวลา.
        /// </summary>
        public static string propRptBillPayment_HeadtimeTest {
            get {
                return ResourceManager.GetString("propRptBillPayment_HeadtimeTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แก้ไข.
        /// </summary>
        public static string propSingleApplicant_004 {
            get {
                return ResourceManager.GetString("propSingleApplicant_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่อนุมัติการสมัคร.
        /// </summary>
        public static string propSite1_ApproveN {
            get {
                return ResourceManager.GetString("propSite1_ApproveN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อนุมัติการสมัคร.
        /// </summary>
        public static string propSite1_ApproveY {
            get {
                return ResourceManager.GetString("propSite1_ApproveY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เจ้าหน้าที่คปภ.Admin.
        /// </summary>
        public static string propSite1_OICAdmin {
            get {
                return ResourceManager.GetString("propSite1_OICAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คปภ. ตัวแทน.
        /// </summary>
        public static string propSite1_OICAgent {
            get {
                return ResourceManager.GetString("propSite1_OICAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คปภ. การเงิน.
        /// </summary>
        public static string propSite1_OICFinace {
            get {
                return ResourceManager.GetString("propSite1_OICFinace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่อนุมัติ.
        /// </summary>
        public static string propSysMessage_LicenseApproveN {
            get {
                return ResourceManager.GetString("propSysMessage_LicenseApproveN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อนุมัติ.
        /// </summary>
        public static string propSysMessage_LicenseApproveP {
            get {
                return ResourceManager.GetString("propSysMessage_LicenseApproveP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รออนุมัติ.
        /// </summary>
        public static string propSysMessage_LicenseApproveW {
            get {
                return ResourceManager.GetString("propSysMessage_LicenseApproveW", resourceCulture);
            }
        }
    }
}
