//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAS.BLL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IAS.BLL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลการลงทะเบียนนี้ถูกยกเลิกการใช้งานแล้ว..
        /// </summary>
        internal static string CancelRegistrationState {
            get {
                return ResourceManager.GetString("CancelRegistrationState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่มีข้อมูล.
        /// </summary>
        internal static string errorApplicantBiz_001 {
            get {
                return ResourceManager.GetString("errorApplicantBiz_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บรรทัดแรก ตำแหน่งแรก ต้องเป็น Header เท่านั้น!.
        /// </summary>
        internal static string errorApplicantBiz_002 {
            get {
                return ResourceManager.GetString("errorApplicantBiz_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบข้อมูลภายในไฟล์นำเข้า.
        /// </summary>
        internal static string errorApplicantBiz_003 {
            get {
                return ResourceManager.GetString("errorApplicantBiz_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถอนุมัติแก้ไขซ้ำได้เนื่องจากข้อมูลการลงทะเบียนได้รับการอนุมัติแก้ไขแล้ว..
        /// </summary>
        internal static string errorApproveEditRegistrationState_001 {
            get {
                return ResourceManager.GetString("errorApproveEditRegistrationState_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถอนุมัติซ้ำได้เนื่องจากข้อมูลการลงทะเบียนได้รับการอนุมัติแล้ว..
        /// </summary>
        internal static string errorApproveRegistrationState_001 {
            get {
                return ResourceManager.GetString("errorApproveRegistrationState_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานะเอกสารไม่ถูกต้อง..
        /// </summary>
        internal static string errorAttachFileStatus_001 {
            get {
                return ResourceManager.GetString("errorAttachFileStatus_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มไฟล์ได้ประเภทละ 1 ไฟล์เท่านั้น!!!.
        /// </summary>
        internal static string errorBasePersonal_001 {
            get {
                return ResourceManager.GetString("errorBasePersonal_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สิทธิ์การอนุมัติเฉพาะเจ้าหน้าผู้ดูแลระบบเท่านั้น..
        /// </summary>
        internal static string errorBaseRegistration_002 {
            get {
                return ResourceManager.GetString("errorBaseRegistration_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบไฟล์ที่ระบุ!!!.
        /// </summary>
        internal static string errorBaseRegistration_003 {
            get {
                return ResourceManager.GetString("errorBaseRegistration_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบเอกสารแนบตามประเภทที่ต้องการ !!!.
        /// </summary>
        internal static string errorBaseRegistration_004 {
            get {
                return ResourceManager.GetString("errorBaseRegistration_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถบันทึกข้อมูลได้เนื่องไฟล์นี้ได้ถูกสั่งลบไปแล้ว..
        /// </summary>
        internal static string errorDeleteAttachFileState_001 {
            get {
                return ResourceManager.GetString("errorDeleteAttachFileState_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถอนุมัติซ้ำได้เนื่องจากข้อมูลการลงทะเบียนได้รับการปฏิเสธแล้ว..
        /// </summary>
        internal static string errorDisapproveEditRegistrationState_001 {
            get {
                return ResourceManager.GetString("errorDisapproveEditRegistrationState_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถอนุมัติแก้ไขซ้ำได้เนื่องจากข้อมูลการลงทะเบียนได้รับการปฏิเสธแล้ว..
        /// </summary>
        internal static string errorDisapproveRegistrationState_001 {
            get {
                return ResourceManager.GetString("errorDisapproveRegistrationState_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บรรทัดแรกต้องเป็น Header เท่านั้น!.
        /// </summary>
        internal static string errorExamResultBiz_001 {
            get {
                return ResourceManager.GetString("errorExamResultBiz_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไฟล์นำเข้าไม่มีข้อมูล.
        /// </summary>
        internal static string errorExamResultBiz_002 {
            get {
                return ResourceManager.GetString("errorExamResultBiz_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาแนบไฟล์.
        /// </summary>
        internal static string errorExamResultBiz_003 {
            get {
                return ResourceManager.GetString("errorExamResultBiz_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่อนุมัติ.
        /// </summary>
        internal static string errorExportBiz_001 {
            get {
                return ResourceManager.GetString("errorExportBiz_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อนุมัติ.
        /// </summary>
        internal static string errorExportBiz_002 {
            get {
                return ResourceManager.GetString("errorExportBiz_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รออนุมัติ.
        /// </summary>
        internal static string errorExportBiz_003 {
            get {
                return ResourceManager.GetString("errorExportBiz_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไฟล์ข้อมูลไม่ถูกต้อง..
        /// </summary>
        internal static string errorLicenseBiz_001 {
            get {
                return ResourceManager.GetString("errorLicenseBiz_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลการลงทะเบียนไม่อยู่ในสถานะรออนุมัติ ไม่สามารถอนุมัติข้อมูลการลงทะเบียนได้..
        /// </summary>
        internal static string errorNewRegistrationState_001 {
            get {
                return ResourceManager.GetString("errorNewRegistrationState_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พบปัญหาในการบันทึกข้อมูลการลงทะเบียน :.
        /// </summary>
        internal static string errorNewRegistrationState_002 {
            get {
                return ResourceManager.GetString("errorNewRegistrationState_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไฟล์ข้อมูลไม่ถูกต้อง.
        /// </summary>
        internal static string errorPaymentBiz_001 {
            get {
                return ResourceManager.GetString("errorPaymentBiz_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระบุธนาคารไม่ถูกต้อง..
        /// </summary>
        internal static string errorPaymentBiz_002 {
            get {
                return ResourceManager.GetString("errorPaymentBiz_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลไม่ถูกต้อง.
        /// </summary>
        internal static string errorPersonBiz_001 {
            get {
                return ResourceManager.GetString("errorPersonBiz_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบข้อมูล .
        /// </summary>
        internal static string errorPersonBiz_002 {
            get {
                return ResourceManager.GetString("errorPersonBiz_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ในระบบ..
        /// </summary>
        internal static string errorPersonBiz_003 {
            get {
                return ResourceManager.GetString("errorPersonBiz_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุ รหัสผ่านให้เรียบรอ้ย.
        /// </summary>
        internal static string errorRegistrationBiz_001 {
            get {
                return ResourceManager.GetString("errorRegistrationBiz_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบข้อมูล เลขบัตรประชาชน..
        /// </summary>
        internal static string errorRegistrationFactory_001 {
            get {
                return ResourceManager.GetString("errorRegistrationFactory_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถลบได้ เนื่องจากรายการสอบได้ผ่านมาแล้ว.
        /// </summary>
        internal static string errorSysMessage_CannotDeleteExamTestingNo {
            get {
                return ResourceManager.GetString("errorSysMessage_CannotDeleteExamTestingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถแก้ไขได้ เนื่องจากรายการสอบได้ผ่านมาแล้ว.
        /// </summary>
        internal static string errorSysMessage_CannotEditExamTestingNo {
            get {
                return ResourceManager.GetString("errorSysMessage_CannotEditExamTestingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถโหลดไฟล์ได้ เนื่องจากกรอกรายการไม่ครบ.
        /// </summary>
        internal static string errorSysMessage_CannotUploadFile {
            get {
                return ResourceManager.GetString("errorSysMessage_CannotUploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Data Empty : .
        /// </summary>
        internal static string errorSysMessage_DataEmpty {
            get {
                return ResourceManager.GetString("errorSysMessage_DataEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รูปแบบอีเมลไม่ถูกต้อง กรุณากรอกใหม่.
        /// </summary>
        internal static string errorSysMessage_EmailErrorFormat {
            get {
                return ResourceManager.GetString("errorSysMessage_EmailErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผิดพลาด.
        /// </summary>
        internal static string errorSysMessage_Fail {
            get {
                return ResourceManager.GetString("errorSysMessage_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่มีข้อมูลในระบบ.
        /// </summary>
        internal static string errorSysMessage_NoData {
            get {
                return ResourceManager.GetString("errorSysMessage_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสผ่านไม่ตรงกัน.
        /// </summary>
        internal static string errorSysMessage_NotSame {
            get {
                return ResourceManager.GetString("errorSysMessage_NotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสผ่านใหม่ห้ามตรงกับรหัสผ่านเก่า.
        /// </summary>
        internal static string errorSysMessage_PleaseChangeDefault {
            get {
                return ResourceManager.GetString("errorSysMessage_PleaseChangeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกประเภทสมาชิก OIC.
        /// </summary>
        internal static string errorSysMessage_PleaseChooesTypeMemberOIC {
            get {
                return ResourceManager.GetString("errorSysMessage_PleaseChooesTypeMemberOIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกประเภทไฟล์ให้ถูกต้อง.
        /// </summary>
        internal static string errorSysMessage_PleaseChooseFile {
            get {
                return ResourceManager.GetString("errorSysMessage_PleaseChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ท่านยังไม่ได้เลือกประเภทการลงทะเบียน.
        /// </summary>
        internal static string errorSysMessage_PleaseChooseMemberType {
            get {
                return ResourceManager.GetString("errorSysMessage_PleaseChooseMemberType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาลบไฟล์เก่าก่อน ที่จะ Upload ใหม่.
        /// </summary>
        internal static string errorSysMessage_PleaseDeleteFile {
            get {
                return ResourceManager.GetString("errorSysMessage_PleaseDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกข้อมูลบริษัทให้ถูกต้อง.
        /// </summary>
        internal static string errorSysMessage_PleaseInputCompany {
            get {
                return ResourceManager.GetString("errorSysMessage_PleaseInputCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกข้อมูลให้ครบ.
        /// </summary>
        internal static string errorSysMessage_PleaseInputFill {
            get {
                return ResourceManager.GetString("errorSysMessage_PleaseInputFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกรหัสสอบให้ถูกต้อง.
        /// </summary>
        internal static string errorSysMessage_PleaseInputTestingNo {
            get {
                return ResourceManager.GetString("errorSysMessage_PleaseInputTestingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกรหัสผ่านใหม่ให้ตรงกับยืนยันรหัสผ่าน.
        /// </summary>
        internal static string errorSysMessage_PleaseSamePassword {
            get {
                return ResourceManager.GetString("errorSysMessage_PleaseSamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกไฟล์นามสกุลให้ถูกต้อง.
        /// </summary>
        internal static string errorSysMessage_PleaseSelectFile {
            get {
                return ResourceManager.GetString("errorSysMessage_PleaseSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกไฟล์นามสกุล .txt ให้ถูกต้อง.
        /// </summary>
        internal static string errorSysMessage_PleaseSelectFileTxt {
            get {
                return ResourceManager.GetString("errorSysMessage_PleaseSelectFileTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เกิดข้อผิดพลาดจาก Server.
        /// </summary>
        internal static string errorSysMessage_ServerError {
            get {
                return ResourceManager.GetString("errorSysMessage_ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาตรวจสอบข้อมูลใหม่.
        /// </summary>
        internal static string errorSysMessage_TryAgain {
            get {
                return ResourceManager.GetString("errorSysMessage_TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุตำแหน่งเอกสารให้ถูกต้อง..
        /// </summary>
        internal static string errorUploadDataBiz_001 {
            get {
                return ResourceManager.GetString("errorUploadDataBiz_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูล ไฟล์แนบไม่ถูกต้อง:.
        /// </summary>
        internal static string errorUploadDataBiz_002 {
            get {
                return ResourceManager.GetString("errorUploadDataBiz_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were problems saving the Basket:.
        /// </summary>
        internal static string infoDisapproveRegistrationState_002 {
            get {
                return ResourceManager.GetString("infoDisapproveRegistrationState_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อนุมัติเรียบร้อย.
        /// </summary>
        internal static string infoSysMessage_Approval {
            get {
                return ResourceManager.GetString("infoSysMessage_Approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาติ๊กข้อมูลการยอมรับ.
        /// </summary>
        internal static string infoSysMessage_CheckCondition {
            get {
                return ResourceManager.GetString("infoSysMessage_CheckCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกข้อมูล.
        /// </summary>
        internal static string infoSysMessage_ChooseData {
            get {
                return ResourceManager.GetString("infoSysMessage_ChooseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือก.
        /// </summary>
        internal static string infoSysMessage_DefaultSelecting {
            get {
                return ResourceManager.GetString("infoSysMessage_DefaultSelecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete File.
        /// </summary>
        internal static string infoSysMessage_DeleteFile {
            get {
                return ResourceManager.GetString("infoSysMessage_DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ท่านได้เคยทำการลงทะเบียนสมาชิกไว้แล้วกรุณากลับไปหน้าแรกเพื่อทำการ Login.
        /// </summary>
        internal static string infoSysMessage_DialogLoginFail {
            get {
                return ResourceManager.GetString("infoSysMessage_DialogLoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลงทะเบียน.
        /// </summary>
        internal static string infoSysMessage_DialogLoginTitle {
            get {
                return ResourceManager.GetString("infoSysMessage_DialogLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกหมายเลขบริษัท.
        /// </summary>
        internal static string infoSysMessage_PleaseInputCompCode {
            get {
                return ResourceManager.GetString("infoSysMessage_PleaseInputCompCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกข้อมูลบัตรประชาชน.
        /// </summary>
        internal static string infoSysMessage_PleaseInputIDNumber {
            get {
                return ResourceManager.GetString("infoSysMessage_PleaseInputIDNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกวัน.
        /// </summary>
        internal static string infoSysMessage_PleaseSelectDate {
            get {
                return ResourceManager.GetString("infoSysMessage_PleaseSelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกไฟล์.
        /// </summary>
        internal static string infoSysMessage_PleaseSelectFileData {
            get {
                return ResourceManager.GetString("infoSysMessage_PleaseSelectFileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สมัครสมาชิกเรียบร้อยแล้วขอบคุณค่ะ.
        /// </summary>
        internal static string infoSysMessage_SaveAssociationSuccess {
            get {
                return ResourceManager.GetString("infoSysMessage_SaveAssociationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทำการบันทึกข้อมูลเรียบร้อย.
        /// </summary>
        internal static string infoSysMessage_SaveSucess {
            get {
                return ResourceManager.GetString("infoSysMessage_SaveSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        internal static string infoSysMessage_SelectFile {
            get {
                return ResourceManager.GetString("infoSysMessage_SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นำเข้าระบบเรียบร้อย.
        /// </summary>
        internal static string infoSysMessage_SuccessImportData {
            get {
                return ResourceManager.GetString("infoSysMessage_SuccessImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มการสมัครเรียบร้อย.
        /// </summary>
        internal static string infoSysMessage_SuccessInsertApplicant {
            get {
                return ResourceManager.GetString("infoSysMessage_SuccessInsertApplicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มการขอใบอนุญาตเรียบร้อย.
        /// </summary>
        internal static string infoSysMessage_SuccessInsertLicenseSingle {
            get {
                return ResourceManager.GetString("infoSysMessage_SuccessInsertLicenseSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มการลงทะเบียนเจ้าหน้าที่กลุ่มสนามสอบ.
        /// </summary>
        internal static string infoSysMessage_SuccessInsertTypeGroupPlace {
            get {
                return ResourceManager.GetString("infoSysMessage_SuccessInsertTypeGroupPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มการลงทะเบียนเจ้าหน้าที่ คปภ..
        /// </summary>
        internal static string infoSysMessage_SuccessInsertTypeOIC {
            get {
                return ResourceManager.GetString("infoSysMessage_SuccessInsertTypeOIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มสมาชิก.
        /// </summary>
        internal static string infoSysMessage_TitleTypeMemberOIC {
            get {
                return ResourceManager.GetString("infoSysMessage_TitleTypeMemberOIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไฟล์แนบ.
        /// </summary>
        internal static string propAttachFileFieldTHNames_Attach_File_Path {
            get {
                return ResourceManager.GetString("propAttachFileFieldTHNames_Attach_File_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสประเภทไฟล์แนบ.
        /// </summary>
        internal static string propAttachFileFieldTHNames_Attach_File_Type {
            get {
                return ResourceManager.GetString("propAttachFileFieldTHNames_Attach_File_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สร้างโดย.
        /// </summary>
        internal static string propAttachFileFieldTHNames_Created_By {
            get {
                return ResourceManager.GetString("propAttachFileFieldTHNames_Created_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สร้างวันที่.
        /// </summary>
        internal static string propAttachFileFieldTHNames_Created_Date {
            get {
                return ResourceManager.GetString("propAttachFileFieldTHNames_Created_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานะเอกสาร.
        /// </summary>
        internal static string propAttachFileFieldTHNames_File_Status {
            get {
                return ResourceManager.GetString("propAttachFileFieldTHNames_File_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสรายการ.
        /// </summary>
        internal static string propAttachFileFieldTHNames_ID {
            get {
                return ResourceManager.GetString("propAttachFileFieldTHNames_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสรายการเลขลงทะเบียน.
        /// </summary>
        internal static string propAttachFileFieldTHNames_Registration_ID {
            get {
                return ResourceManager.GetString("propAttachFileFieldTHNames_Registration_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเหตุ.
        /// </summary>
        internal static string propAttachFileFieldTHNames_Remark {
            get {
                return ResourceManager.GetString("propAttachFileFieldTHNames_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แก้ไขโดย.
        /// </summary>
        internal static string propAttachFileFieldTHNames_Updated_By {
            get {
                return ResourceManager.GetString("propAttachFileFieldTHNames_Updated_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แก้ไขเมื่อวันที่.
        /// </summary>
        internal static string propAttachFileFieldTHNames_Updated_Date {
            get {
                return ResourceManager.GetString("propAttachFileFieldTHNames_Updated_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่อยู่ 1.
        /// </summary>
        internal static string propTHRegFieldNames_ADDRESS_1 {
            get {
                return ResourceManager.GetString("propTHRegFieldNames_ADDRESS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่อยู่ 2.
        /// </summary>
        internal static string propTHRegFieldNames_ADDRESS_2 {
            get {
                return ResourceManager.GetString("propTHRegFieldNames_ADDRESS_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสพื้นที่.
        /// </summary>
        internal static string propTHRegFieldNames_AREA_CODE {
            get {
                return ResourceManager.GetString("propTHRegFieldNames_AREA_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันเดือนปีเกิด.
        /// </summary>
        internal static string propTHRegFieldNames_BIRTH_DATE {
            get {
                return ResourceManager.GetString("propTHRegFieldNames_BIRTH_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานะใช้งาน.
        /// </summary>
        internal static string propTHRegFieldNames_COMP_CODE {
            get {
                return ResourceManager.GetString("propTHRegFieldNames_COMP_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสวุฒิการศึกษา.
        /// </summary>
        internal static string propTHRegFieldNames_EDUCATION_CODE {
            get {
                return ResourceManager.GetString("propTHRegFieldNames_EDUCATION_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อีเมล.
        /// </summary>
        internal static string propTHRegFieldNames_EMAIL {
            get {
                return ResourceManager.GetString("propTHRegFieldNames_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสพนักงาน / รหัสเจ้าหน้าที่.
        /// </summary>
        internal static string propTHRegFieldNames_EMPLOYEE_NO {
            get {
                return ResourceManager.GetString("propTHRegFieldNames_EMPLOYEE_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขประจำตัวประชาชน.
        /// </summary>
        internal static string propTHRegFieldNames_ID_CARD_NO {
            get {
                return ResourceManager.GetString("propTHRegFieldNames_ID_CARD_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นามสกุล.
        /// </summary>
        internal static string propTHRegFieldNames_LASTNAME {
            get {
                return ResourceManager.GetString("propTHRegFieldNames_LASTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่อยู่ตามภูมิลำเนา1.
        /// </summary>
        internal static string propTHRegFieldNames_LOCAL_ADDRESS1 {
            get {
                return ResourceManager.GetString("propTHRegFieldNames_LOCAL_ADDRESS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่อยู่ตามภูมิลำเนา2.
        /// </summary>
        internal static string propTHRegFieldNames_LOCAL_ADDRESS2 {
            get {
                return ResourceManager.GetString("propTHRegFieldNames_LOCAL_ADDRESS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสพื้นที่ตามภูมิลำเนา.
        /// </summary>
        internal static string propTHRegFieldNames_LOCAL_AREA_CODE {
            get {
                return ResourceManager.GetString("propTHRegFieldNames_LOCAL_AREA_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสจังหวัดตามภูมิลำเนา.
        /// </summary>
        internal static string propTHRegFieldNames_LOCAL_PROVINCE_CODE {
            get {
                return ResourceManager.GetString("propTHRegFieldNames_LOCAL_PROVINCE_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โทรศัพท์ตามภูมิลำเนา.
        /// </summary>
        internal static string propTHRegFieldNames_LOCAL_TELEPHONE {
            get {
                return ResourceManager.GetString("propTHRegFieldNames_LOCAL_TELEPHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสผ่านที่ลงทะเบียน.
        /// </summary>
        internal static string propTHRegFieldNames_LOCAL_TUMBON_CODE {
            get {
                return ResourceManager.GetString("propTHRegFieldNames_LOCAL_TUMBON_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสไปรษณีย์ตามภูมิลำเนา.
        /// </summary>
        internal static string propTHRegFieldNames_LOCAL_ZIPCODE {
            get {
                return ResourceManager.GetString("propTHRegFieldNames_LOCAL_ZIPCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสประเภท.
        /// </summary>
        internal static string propTHRegFieldNames_Member_Type {
            get {
                return ResourceManager.GetString("propTHRegFieldNames_Member_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อ.
        /// </summary>
        internal static string propTHRegFieldNames_NAMES {
            get {
                return ResourceManager.GetString("propTHRegFieldNames_NAMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สัญชาติ.
        /// </summary>
        internal static string propTHRegFieldNames_NATIONNALITY {
            get {
                return ResourceManager.GetString("propTHRegFieldNames_NATIONNALITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสคำนำหน้า.
        /// </summary>
        internal static string propTHRegFieldNames_PRE_NAME_CODE {
            get {
                return ResourceManager.GetString("propTHRegFieldNames_PRE_NAME_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสจังหวัด.
        /// </summary>
        internal static string propTHRegFieldNames_PROVINCE_CODE {
            get {
                return ResourceManager.GetString("propTHRegFieldNames_PROVINCE_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพศ ช = เพศชาย, ญ = เพศหญิง.
        /// </summary>
        internal static string propTHRegFieldNames_SEX {
            get {
                return ResourceManager.GetString("propTHRegFieldNames_SEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสตำบล.
        /// </summary>
        internal static string propTHRegFieldNames_STATUS {
            get {
                return ResourceManager.GetString("propTHRegFieldNames_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โทรศัพท์.
        /// </summary>
        internal static string propTHRegFieldNames_TELEPHONE {
            get {
                return ResourceManager.GetString("propTHRegFieldNames_TELEPHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสตำบลตามภูมิลำเนา.
        /// </summary>
        internal static string propTHRegFieldNames_TUMBON_CODE {
            get {
                return ResourceManager.GetString("propTHRegFieldNames_TUMBON_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสไปรษณีย์.
        /// </summary>
        internal static string propTHRegFieldNames_ZIP_CODE {
            get {
                return ResourceManager.GetString("propTHRegFieldNames_ZIP_CODE", resourceCulture);
            }
        }
    }
}
