//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAS.EmailSmtpService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttachStream", Namespace="http://schemas.datacontract.org/2004/07/IAS.Common.Email")]
    [System.SerializableAttribute()]
    public partial class AttachStream : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.IO.Stream FileStreamField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.IO.Stream FileStream {
            get {
                return this.FileStreamField;
            }
            set {
                if ((object.ReferenceEquals(this.FileStreamField, value) != true)) {
                    this.FileStreamField = value;
                    this.RaisePropertyChanged("FileStream");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmailSmtpService.IEmailSmtpService")]
    public interface IEmailSmtpService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailSmtpService/SendMail", ReplyAction="http://tempuri.org/IEmailSmtpService/SendMailResponse")]
        void SendMail(string from, string to, string subject, string body);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailSmtpService/SendMailWithAttachment", ReplyAction="http://tempuri.org/IEmailSmtpService/SendMailWithAttachmentResponse")]
        void SendMailWithAttachment(string from, string to, string subject, string body, IAS.EmailSmtpService.AttachStream[] attachFiles);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmailSmtpServiceChannel : IAS.EmailSmtpService.IEmailSmtpService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmailSmtpServiceClient : System.ServiceModel.ClientBase<IAS.EmailSmtpService.IEmailSmtpService>, IAS.EmailSmtpService.IEmailSmtpService {
        
        public EmailSmtpServiceClient() {
        }
        
        public EmailSmtpServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmailSmtpServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailSmtpServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailSmtpServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendMail(string from, string to, string subject, string body) {
            base.Channel.SendMail(from, to, subject, body);
        }
        
        public void SendMailWithAttachment(string from, string to, string subject, string body, IAS.EmailSmtpService.AttachStream[] attachFiles) {
            base.Channel.SendMailWithAttachment(from, to, subject, body, attachFiles);
        }
    }
}
