//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAS.FileManagement {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileManagement.IFileService")]
    public interface IFileService {
        
        // CODEGEN: Generating message contract since the wrapper name (FileUploadMessage) of message FileUploadMessage does not match the default value (UploadFile)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/UploadFile", ReplyAction="http://tempuri.org/IFileService/UploadFileResponse")]
        IAS.FileManagement.FileUploadMessage UploadFile(IAS.FileManagement.FileUploadMessage request);
        
        // CODEGEN: Generating message contract since the wrapper name (FileDownloadMessage) of message FileDownloadMessage does not match the default value (DownloadFile)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/DownloadFile", ReplyAction="http://tempuri.org/IFileService/DownloadFileResponse")]
        IAS.FileManagement.FileDownloadReturnMessage DownloadFile(IAS.FileManagement.FileDownloadMessage request);
        
        // CODEGEN: Generating message contract since the wrapper name (DownloadRequest) of message DownloadRequest does not match the default value (DownloadFileSign)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/DownloadFileSign", ReplyAction="http://tempuri.org/IFileService/DownloadFileSignResponse")]
        IAS.FileManagement.RemoteFileInfo DownloadFileSign(IAS.FileManagement.DownloadRequest request);
        
        // CODEGEN: Generating message contract since the operation UpdateOIC is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/UpdateOIC", ReplyAction="http://tempuri.org/IFileService/UpdateOICResponse")]
        IAS.FileManagement.UpdateOICResponse UpdateOIC(IAS.FileManagement.RemoteFileInfo request);
        
        // CODEGEN: Generating message contract since the operation InsertOIC is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/InsertOIC", ReplyAction="http://tempuri.org/IFileService/InsertOICResponse")]
        IAS.FileManagement.InsertOICResponse InsertOIC(IAS.FileManagement.RemoteFileInfoAddOic request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileUploadMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FileUploadMessage {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public IAS.BLL.FileManagement.FileMetaData Metadata;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileByteStream;
        
        public FileUploadMessage() {
        }
        
        public FileUploadMessage(IAS.BLL.FileManagement.FileMetaData Metadata, System.IO.Stream FileByteStream) {
            this.Metadata = Metadata;
            this.FileByteStream = FileByteStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileDownloadMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FileDownloadMessage {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public IAS.BLL.FileManagement.FileMetaData FileMetaData;
        
        public FileDownloadMessage() {
        }
        
        public FileDownloadMessage(IAS.BLL.FileManagement.FileMetaData FileMetaData) {
            this.FileMetaData = FileMetaData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileDownloadReturnMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FileDownloadReturnMessage {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public IAS.BLL.FileManagement.FileMetaData DownloadedFileMetadata;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileByteStream;
        
        public FileDownloadReturnMessage() {
        }
        
        public FileDownloadReturnMessage(IAS.BLL.FileManagement.FileMetaData DownloadedFileMetadata, System.IO.Stream FileByteStream) {
            this.DownloadedFileMetadata = DownloadedFileMetadata;
            this.FileByteStream = FileByteStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Id;
        
        public DownloadRequest() {
        }
        
        public DownloadRequest(string Id) {
            this.Id = Id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoteFileInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoteFileInfo {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string firstName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string lastName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string memberType;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string oicUserName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string preNameCode;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string sex;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileByteStream;
        
        public RemoteFileInfo() {
        }
        
        public RemoteFileInfo(string firstName, string lastName, string memberType, string oicUserName, string preNameCode, string sex, string userId, System.IO.Stream FileByteStream) {
            this.firstName = firstName;
            this.lastName = lastName;
            this.memberType = memberType;
            this.oicUserName = oicUserName;
            this.preNameCode = preNameCode;
            this.sex = sex;
            this.userId = userId;
            this.FileByteStream = FileByteStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateOICResponse {
        
        public UpdateOICResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoteFileInfoAddOic", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoteFileInfoAddOic {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string firstName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string lastName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string oicEmpNo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string oicTypeCode;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string oicUserName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string preNameCode;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string sex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileByteStream;
        
        public RemoteFileInfoAddOic() {
        }
        
        public RemoteFileInfoAddOic(string firstName, string lastName, string oicEmpNo, string oicTypeCode, string oicUserName, string preNameCode, string sex, System.IO.Stream FileByteStream) {
            this.firstName = firstName;
            this.lastName = lastName;
            this.oicEmpNo = oicEmpNo;
            this.oicTypeCode = oicTypeCode;
            this.oicUserName = oicUserName;
            this.preNameCode = preNameCode;
            this.sex = sex;
            this.FileByteStream = FileByteStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertOICResponse {
        
        public InsertOICResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileServiceChannel : IAS.FileManagement.IFileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileServiceClient : System.ServiceModel.ClientBase<IAS.FileManagement.IFileService>, IAS.FileManagement.IFileService {
        
        public FileServiceClient() {
        }
        
        public FileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IAS.FileManagement.FileUploadMessage IAS.FileManagement.IFileService.UploadFile(IAS.FileManagement.FileUploadMessage request) {
            return base.Channel.UploadFile(request);
        }
        
        public void UploadFile(ref IAS.BLL.FileManagement.FileMetaData Metadata, ref System.IO.Stream FileByteStream) {
            IAS.FileManagement.FileUploadMessage inValue = new IAS.FileManagement.FileUploadMessage();
            inValue.Metadata = Metadata;
            inValue.FileByteStream = FileByteStream;
            IAS.FileManagement.FileUploadMessage retVal = ((IAS.FileManagement.IFileService)(this)).UploadFile(inValue);
            Metadata = retVal.Metadata;
            FileByteStream = retVal.FileByteStream;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IAS.FileManagement.FileDownloadReturnMessage IAS.FileManagement.IFileService.DownloadFile(IAS.FileManagement.FileDownloadMessage request) {
            return base.Channel.DownloadFile(request);
        }
        
        public IAS.BLL.FileManagement.FileMetaData DownloadFile(IAS.BLL.FileManagement.FileMetaData FileMetaData, out System.IO.Stream FileByteStream) {
            IAS.FileManagement.FileDownloadMessage inValue = new IAS.FileManagement.FileDownloadMessage();
            inValue.FileMetaData = FileMetaData;
            IAS.FileManagement.FileDownloadReturnMessage retVal = ((IAS.FileManagement.IFileService)(this)).DownloadFile(inValue);
            FileByteStream = retVal.FileByteStream;
            return retVal.DownloadedFileMetadata;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IAS.FileManagement.RemoteFileInfo IAS.FileManagement.IFileService.DownloadFileSign(IAS.FileManagement.DownloadRequest request) {
            return base.Channel.DownloadFileSign(request);
        }
        
        public string DownloadFileSign(string Id, out string lastName, out string memberType, out string oicUserName, out string preNameCode, out string sex, out string userId, out System.IO.Stream FileByteStream) {
            IAS.FileManagement.DownloadRequest inValue = new IAS.FileManagement.DownloadRequest();
            inValue.Id = Id;
            IAS.FileManagement.RemoteFileInfo retVal = ((IAS.FileManagement.IFileService)(this)).DownloadFileSign(inValue);
            lastName = retVal.lastName;
            memberType = retVal.memberType;
            oicUserName = retVal.oicUserName;
            preNameCode = retVal.preNameCode;
            sex = retVal.sex;
            userId = retVal.userId;
            FileByteStream = retVal.FileByteStream;
            return retVal.firstName;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IAS.FileManagement.UpdateOICResponse IAS.FileManagement.IFileService.UpdateOIC(IAS.FileManagement.RemoteFileInfo request) {
            return base.Channel.UpdateOIC(request);
        }
        
        public void UpdateOIC(string firstName, string lastName, string memberType, string oicUserName, string preNameCode, string sex, string userId, System.IO.Stream FileByteStream) {
            IAS.FileManagement.RemoteFileInfo inValue = new IAS.FileManagement.RemoteFileInfo();
            inValue.firstName = firstName;
            inValue.lastName = lastName;
            inValue.memberType = memberType;
            inValue.oicUserName = oicUserName;
            inValue.preNameCode = preNameCode;
            inValue.sex = sex;
            inValue.userId = userId;
            inValue.FileByteStream = FileByteStream;
            IAS.FileManagement.UpdateOICResponse retVal = ((IAS.FileManagement.IFileService)(this)).UpdateOIC(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IAS.FileManagement.InsertOICResponse IAS.FileManagement.IFileService.InsertOIC(IAS.FileManagement.RemoteFileInfoAddOic request) {
            return base.Channel.InsertOIC(request);
        }
        
        public void InsertOIC(string firstName, string lastName, string oicEmpNo, string oicTypeCode, string oicUserName, string preNameCode, string sex, System.IO.Stream FileByteStream) {
            IAS.FileManagement.RemoteFileInfoAddOic inValue = new IAS.FileManagement.RemoteFileInfoAddOic();
            inValue.firstName = firstName;
            inValue.lastName = lastName;
            inValue.oicEmpNo = oicEmpNo;
            inValue.oicTypeCode = oicTypeCode;
            inValue.oicUserName = oicUserName;
            inValue.preNameCode = preNameCode;
            inValue.sex = sex;
            inValue.FileByteStream = FileByteStream;
            IAS.FileManagement.InsertOICResponse retVal = ((IAS.FileManagement.IFileService)(this)).InsertOIC(inValue);
        }
    }
}
