/*
Navicat Oracle Data Transfer
Oracle Client Version : 11.2.0.3.0

Source Server         : AGDOI
Source Server Version : 90200
Source Host           : :1521
Source Schema         : AGDOI

Target Server Type    : ORACLE
Target Server Version : 90200
File Encoding         : 65001

Date: 2014-04-09 14:39:24
*/


-- ----------------------------
-- Table structure for AG_APPLICANT_SCORE_T
-- ----------------------------

CREATE TABLE "AGDOI"."AG_APPLICANT_SCORE_T" (
"APPLICANT_CODE" NUMBER(6) NOT NULL ,
"TESTING_NO" VARCHAR2(6 BYTE) NOT NULL ,
"EXAM_PLACE_CODE" VARCHAR2(6 BYTE) NOT NULL ,
"SUBJECT_CODE" VARCHAR2(3 BYTE) NOT NULL ,
"SCORE" NUMBER(3) NULL ,
"LICENSE_TYPE_CODE" VARCHAR2(2 BYTE) NULL ,
"USER_ID" VARCHAR2(15 BYTE) NULL ,
"USER_DATE" DATE NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "AGDOI"."AG_APPLICANT_SCORE_T" IS '???????????????????';
COMMENT ON COLUMN "AGDOI"."AG_APPLICANT_SCORE_T"."APPLICANT_CODE" IS '??????????????? (???????????????)';
COMMENT ON COLUMN "AGDOI"."AG_APPLICANT_SCORE_T"."TESTING_NO" IS '???????????? (??????????)';
COMMENT ON COLUMN "AGDOI"."AG_APPLICANT_SCORE_T"."EXAM_PLACE_CODE" IS '???????????';
COMMENT ON COLUMN "AGDOI"."AG_APPLICANT_SCORE_T"."SUBJECT_CODE" IS '????????';
COMMENT ON COLUMN "AGDOI"."AG_APPLICANT_SCORE_T"."SCORE" IS '???????????';
COMMENT ON COLUMN "AGDOI"."AG_APPLICANT_SCORE_T"."LICENSE_TYPE_CODE" IS '??????????????????';
COMMENT ON COLUMN "AGDOI"."AG_APPLICANT_SCORE_T"."USER_ID" IS '?????????';
COMMENT ON COLUMN "AGDOI"."AG_APPLICANT_SCORE_T"."USER_DATE" IS '????????????';

-- ----------------------------
-- Indexes structure for table AG_APPLICANT_SCORE_T
-- ----------------------------
CREATE INDEX "AGDOI"."AGIN_APPS_CODE_NEW"
ON "AGDOI"."AG_APPLICANT_SCORE_T" ("APPLICANT_CODE" ASC)
LOGGING;
CREATE INDEX "AGDOI"."AGIN_APPS_LICENSE_TYPE_NEW"
ON "AGDOI"."AG_APPLICANT_SCORE_T" ("LICENSE_TYPE_CODE" ASC)
LOGGING;
CREATE INDEX "AGDOI"."AGIN_APPS_PLACE_NEW"
ON "AGDOI"."AG_APPLICANT_SCORE_T" ("TESTING_NO" ASC, "EXAM_PLACE_CODE" ASC)
LOGGING;
CREATE INDEX "AGDOI"."AGIN_APPS_SCORE_NEW"
ON "AGDOI"."AG_APPLICANT_SCORE_T" ("SUBJECT_CODE" ASC)
LOGGING;
CREATE INDEX "AGDOI"."AGIN_APPS_TEST_NO_INX"
ON "AGDOI"."AG_APPLICANT_SCORE_T" ("TESTING_NO" ASC)
LOGGING;

-- ----------------------------
-- Triggers structure for table AG_APPLICANT_SCORE_T
-- ----------------------------
CREATE OR REPLACE TRIGGER "AGDOI"."AG_APPLICANT_SCORE_TRG_NEW" BEFORE INSERT OR UPDATE ON "AGDOI"."AG_APPLICANT_SCORE_T" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW
BEGIN
  	:NEW.USER_ID 	:= GET_SYS_USER;
  	:NEW.USER_DATE 	:= SYSDATE;
END;
-- ----------------------------
-- Primary Key structure for table AG_APPLICANT_SCORE_T
-- ----------------------------
ALTER TABLE "AGDOI"."AG_APPLICANT_SCORE_T" ADD PRIMARY KEY ("APPLICANT_CODE", "TESTING_NO", "EXAM_PLACE_CODE", "SUBJECT_CODE");

-- ----------------------------
-- Foreign Key structure for table "AGDOI"."AG_APPLICANT_SCORE_T"
-- ----------------------------
ALTER TABLE "AGDOI"."AG_APPLICANT_SCORE_T" ADD FOREIGN KEY ("SUBJECT_CODE", "LICENSE_TYPE_CODE") REFERENCES "AGDOI"."AG_SUBJECT_R" ("SUBJECT_CODE", "LICENSE_TYPE_CODE");
ALTER TABLE "AGDOI"."AG_APPLICANT_SCORE_T" ADD FOREIGN KEY ("TESTING_NO", "EXAM_PLACE_CODE") REFERENCES "AGDOI"."AG_EXAM_LICENSE_R" ("TESTING_NO", "EXAM_PLACE_CODE");
