/*
Navicat Oracle Data Transfer
Oracle Client Version : 11.2.0.3.0

Source Server         : AGDOI
Source Server Version : 90200
Source Host           : :1521
Source Schema         : AGDOI

Target Server Type    : ORACLE
Target Server Version : 90200
File Encoding         : 65001

Date: 2014-04-08 09:41:27
*/


-- ----------------------------
-- Table structure for AG_IAS_VALIDATE_LICENSE_CON
-- ----------------------------
DROP TABLE "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON";
CREATE TABLE "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" (
"ID" NUMBER NOT NULL ,
"ITEM_GROUP" NUMBER NOT NULL ,
"LICENSE_TYPE_CODE" VARCHAR2(2 BYTE) NOT NULL ,
"STATUS" VARCHAR2(1 BYTE) NULL ,
"PETITION_TYPE_CODE" VARCHAR2(2 BYTE) NOT NULL ,
"RENEW_TIME" NUMBER(2) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of AG_IAS_VALIDATE_LICENSE_CON
-- ----------------------------
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('1', '1', '01', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('2', '2', '01', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('3', '3', '01', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('4', '4', '01', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('5', '5', '01', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('6', '1', '01', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('7', '1', '01', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('13', '1', '01', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('14', '5', '01', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('1', '1', '02', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('2', '2', '02', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('8', '1', '01', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('17', '3', '04', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('4', '4', '02', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('5', '5', '02', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('6', '1', '02', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('9', '1', '01', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('7', '1', '02', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('10', '1', '01', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('8', '1', '02', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('14', '5', '02', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('15', '1', '02', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('16', '1', '02', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('9', '1', '02', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('1', '1', '03', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('2', '2', '03', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('3', '3', '03', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('2', '2', '05', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('5', '5', '03', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('6', '1', '03', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('7', '1', '03', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('8', '1', '03', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('9', '1', '03', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('11', '1', '03', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('13', '1', '03', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('1', '1', '04', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('2', '2', '04', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('17', '3', '06', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('17', '3', '08', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('5', '5', '04', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('6', '1', '04', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('7', '1', '04', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('8', '1', '04', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('9', '1', '04', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('12', '1', '04', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('16', '1', '04', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('14', '5', '04', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('14', '5', '03', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('1', '1', '05', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('5', '5', '05', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('6', '1', '05', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('7', '1', '05', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('8', '1', '05', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('9', '1', '05', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('12', '1', '05', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('16', '1', '05', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('14', '5', '05', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('1', '1', '06', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('2', '2', '06', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('4', '4', '06', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('5', '5', '06', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('6', '1', '06', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('7', '1', '06', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('8', '1', '06', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('9', '1', '06', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('12', '1', '06', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('16', '1', '06', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('14', '5', '06', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('1', '1', '07', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('2', '2', '07', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('3', '3', '07', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('4', '4', '07', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('5', '5', '07', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('6', '1', '07', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('7', '1', '07', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('8', '1', '07', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('9', '1', '07', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('10', '1', '07', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('13', '1', '07', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('14', '5', '07', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('1', '1', '08', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('2', '2', '08', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('4', '4', '01', 'A', '13', '2');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('4', '4', '08', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('5', '5', '08', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('6', '1', '08', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('7', '1', '08', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('8', '1', '08', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('9', '1', '08', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('15', '1', '08', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('14', '5', '08', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('16', '1', '08', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('17', '3', '02', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('17', '3', '05', 'A', '11', '0');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('4', '4', '01', 'A', '13', '1');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('4', '4', '01', 'A', '13', '3');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('18', '5', '01', 'A', '13', '1');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('18', '5', '01', 'A', '13', '2');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('18', '5', '01', 'A', '13', '3');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('4', '4', '02', 'A', '13', '1');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('4', '4', '02', 'A', '13', '2');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('4', '4', '02', 'A', '13', '3');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('18', '5', '02', 'A', '13', '1');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('18', '5', '02', 'A', '13', '2');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('18', '5', '02', 'A', '13', '3');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('4', '4', '03', 'A', '13', '1');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('4', '4', '03', 'A', '13', '2');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('4', '4', '03', 'A', '13', '3');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('18', '5', '03', 'A', '13', '1');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('18', '5', '03', 'A', '13', '2');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('18', '5', '03', 'A', '13', '3');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('4', '4', '04', 'A', '13', '1');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('4', '4', '04', 'A', '13', '2');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('4', '4', '04', 'A', '13', '3');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('18', '5', '04', 'A', '13', '1');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('18', '5', '04', 'A', '13', '2');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('18', '5', '04', 'A', '13', '3');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('18', '5', '05', 'A', '13', '1');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('18', '5', '05', 'A', '13', '2');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('18', '5', '05', 'A', '13', '3');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('18', '5', '06', 'A', '13', '1');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('18', '5', '06', 'A', '13', '2');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('18', '5', '06', 'A', '13', '3');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('4', '4', '07', 'A', '13', '1');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('4', '4', '07', 'A', '13', '2');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('4', '4', '07', 'A', '13', '3');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('18', '5', '07', 'A', '13', '1');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('18', '5', '07', 'A', '13', '2');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('18', '5', '07', 'A', '13', '3');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('4', '4', '08', 'A', '13', '1');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('4', '4', '08', 'A', '13', '2');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('4', '4', '08', 'A', '13', '3');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('18', '5', '08', 'A', '13', '1');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('18', '5', '08', 'A', '13', '2');
INSERT INTO "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" VALUES ('18', '5', '08', 'A', '13', '3');

-- ----------------------------
-- Indexes structure for table AG_IAS_VALIDATE_LICENSE_CON
-- ----------------------------

-- ----------------------------
-- Checks structure for table AG_IAS_VALIDATE_LICENSE_CON
-- ----------------------------
ALTER TABLE "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" ADD CHECK ("ITEM_GROUP" IS NOT NULL);
ALTER TABLE "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" ADD CHECK ("LICENSE_TYPE_CODE" IS NOT NULL);
ALTER TABLE "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" ADD CHECK ("PETITION_TYPE_CODE" IS NOT NULL);
ALTER TABLE "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" ADD CHECK ("RENEW_TIME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table AG_IAS_VALIDATE_LICENSE_CON
-- ----------------------------
ALTER TABLE "AGDOI"."AG_IAS_VALIDATE_LICENSE_CON" ADD PRIMARY KEY ("ID", "ITEM_GROUP", "LICENSE_TYPE_CODE", "PETITION_TYPE_CODE", "RENEW_TIME");
