/*
Navicat Oracle Data Transfer
Oracle Client Version : 11.2.0.3.0

Source Server         : AGDOI
Source Server Version : 90200
Source Host           : :1521
Source Schema         : AGDOI

Target Server Type    : ORACLE
Target Server Version : 90200
File Encoding         : 65001

Date: 2014-05-19 15:57:43
*/


-- ----------------------------
-- Table structure for AG_IAS_PAYMENT_DETAIL
-- ----------------------------
DROP TABLE "AGDOI"."AG_IAS_PAYMENT_DETAIL";
CREATE TABLE "AGDOI"."AG_IAS_PAYMENT_DETAIL" (
"ID" VARCHAR2(15 BYTE) NOT NULL ,
"RECORD_TYPE" VARCHAR2(1 BYTE) NULL ,
"BANK_CODE" VARCHAR2(3 BYTE) NULL ,
"COMPANY_ACCOUNT" VARCHAR2(10 BYTE) NULL ,
"PAYMENT_DATE" VARCHAR2(8 BYTE) NULL ,
"PAYMENT_TIME" VARCHAR2(6 BYTE) NULL ,
"CUSTOMER_NAME" VARCHAR2(70 BYTE) NULL ,
"CUSTOMER_NO_REF1" VARCHAR2(20 BYTE) NULL ,
"REF2" VARCHAR2(20 BYTE) NULL ,
"REF3" VARCHAR2(20 BYTE) NULL ,
"BRANCH_NO" VARCHAR2(4 BYTE) NULL ,
"TELLER_NO" VARCHAR2(4 BYTE) NULL ,
"KIND_OF_TRANSACTION" VARCHAR2(1 BYTE) NULL ,
"TRANSACTION_CODE" VARCHAR2(3 BYTE) NULL ,
"CHEQUE_NO" VARCHAR2(7 BYTE) NULL ,
"AMOUNT" VARCHAR2(13 BYTE) NULL ,
"CHEQUE_BANK_CODE" VARCHAR2(3 BYTE) NULL ,
"HEADER_ID" VARCHAR2(15 BYTE) NULL ,
"STATUS" NUMBER(1) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Checks structure for table AG_IAS_PAYMENT_DETAIL
-- ----------------------------
ALTER TABLE "AGDOI"."AG_IAS_PAYMENT_DETAIL" ADD CHECK ("ID" IS NOT NULL);
