/*
Navicat Oracle Data Transfer
Oracle Client Version : 11.2.0.3.0

Source Server         : AGDOI
Source Server Version : 90200
Source Host           : :1521
Source Schema         : AGDOI

Target Server Type    : ORACLE
Target Server Version : 90200
File Encoding         : 65001

Date: 2014-04-28 17:23:01
*/


-- ----------------------------
-- Table structure for AG_IAS_ASSOCIATION_APPROVE
-- ----------------------------
DROP TABLE "AGDOI"."AG_IAS_ASSOCIATION_APPROVE";
CREATE TABLE "AGDOI"."AG_IAS_ASSOCIATION_APPROVE" (
"ASSOCIATION_APPROVE_ID" NUMBER NOT NULL ,
"ASSOCIATION_CODE" VARCHAR2(5 BYTE) NOT NULL ,
"APPROVE_DOC_TYPE" VARCHAR2(2 BYTE) NOT NULL ,
"STATUS" VARCHAR2(2 BYTE) NOT NULL ,
"CREATE_BY" VARCHAR2(20 BYTE) NOT NULL ,
"CREATE_DATE" DATE NOT NULL ,
"UPDATE_BY" VARCHAR2(20 BYTE) NULL ,
"UPDATE_DATE" DATE NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Indexes structure for table AG_IAS_ASSOCIATION_APPROVE
-- ----------------------------

-- ----------------------------
-- Checks structure for table AG_IAS_ASSOCIATION_APPROVE
-- ----------------------------
ALTER TABLE "AGDOI"."AG_IAS_ASSOCIATION_APPROVE" ADD CHECK ("ASSOCIATION_APPROVE_ID" IS NOT NULL);
ALTER TABLE "AGDOI"."AG_IAS_ASSOCIATION_APPROVE" ADD CHECK ("ASSOCIATION_CODE" IS NOT NULL);
ALTER TABLE "AGDOI"."AG_IAS_ASSOCIATION_APPROVE" ADD CHECK ("APPROVE_DOC_TYPE" IS NOT NULL);
ALTER TABLE "AGDOI"."AG_IAS_ASSOCIATION_APPROVE" ADD CHECK ("STATUS" IS NOT NULL);
ALTER TABLE "AGDOI"."AG_IAS_ASSOCIATION_APPROVE" ADD CHECK ("CREATE_BY" IS NOT NULL);
ALTER TABLE "AGDOI"."AG_IAS_ASSOCIATION_APPROVE" ADD CHECK ("CREATE_DATE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table AG_IAS_ASSOCIATION_APPROVE
-- ----------------------------
ALTER TABLE "AGDOI"."AG_IAS_ASSOCIATION_APPROVE" ADD PRIMARY KEY ("ASSOCIATION_APPROVE_ID");
