/*
Navicat Oracle Data Transfer
Oracle Client Version : 11.2.0.3.0

Source Server         : AGDOI
Source Server Version : 90200
Source Host           : :1521
Source Schema         : AGDOI

Target Server Type    : ORACLE
Target Server Version : 90200
File Encoding         : 65001

Date: 2014-04-09 14:43:49
*/


-- ----------------------------
-- Table structure for AG_PERSON_INCOMP_AGENT_T
-- ----------------------------

CREATE TABLE "AGDOI"."AG_PERSON_INCOMP_AGENT_T" (
"ORDER_NO" NUMBER(7) NULL ,
"COMPANY_CODE" VARCHAR2(4 BYTE) NOT NULL ,
"BRANCH_SEQ" NUMBER(4) NULL ,
"REGISTER_COMP_NO" VARCHAR2(15 BYTE) NULL ,
"COMP_LICENSE_NO" VARCHAR2(15 BYTE) NULL ,
"COMP_LICENSE_TYPE" VARCHAR2(2 BYTE) NULL ,
"LICENSE_NO" VARCHAR2(15 BYTE) NOT NULL ,
"LICENSE_TYPE_CODE" VARCHAR2(2 BYTE) NULL ,
"PERSON_TYPE_CODE" VARCHAR2(2 BYTE) NULL ,
"ID_CARD_NO" VARCHAR2(13 BYTE) NULL ,
"PRE_NAME_CODE" NUMBER(3) NULL ,
"NAME_LASTNAME" VARCHAR2(100 BYTE) NULL ,
"IN_DATE" DATE NOT NULL ,
"OUT_DATE" DATE NULL ,
"SHARE_NO" NUMBER(12,2) NULL ,
"STATUS" VARCHAR2(1 BYTE) NULL ,
"USER_ID" VARCHAR2(15 BYTE) NULL ,
"USER_DATE" DATE NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "AGDOI"."AG_PERSON_INCOMP_AGENT_T" IS '?????????????????????????????';
COMMENT ON COLUMN "AGDOI"."AG_PERSON_INCOMP_AGENT_T"."ORDER_NO" IS '????????';
COMMENT ON COLUMN "AGDOI"."AG_PERSON_INCOMP_AGENT_T"."COMPANY_CODE" IS '??????????';
COMMENT ON COLUMN "AGDOI"."AG_PERSON_INCOMP_AGENT_T"."BRANCH_SEQ" IS '????????????';
COMMENT ON COLUMN "AGDOI"."AG_PERSON_INCOMP_AGENT_T"."REGISTER_COMP_NO" IS '????????????????';
COMMENT ON COLUMN "AGDOI"."AG_PERSON_INCOMP_AGENT_T"."COMP_LICENSE_NO" IS '??????????????????????????????';
COMMENT ON COLUMN "AGDOI"."AG_PERSON_INCOMP_AGENT_T"."COMP_LICENSE_TYPE" IS '???????????????????????????';
COMMENT ON COLUMN "AGDOI"."AG_PERSON_INCOMP_AGENT_T"."LICENSE_NO" IS '?????????????????????';
COMMENT ON COLUMN "AGDOI"."AG_PERSON_INCOMP_AGENT_T"."LICENSE_TYPE_CODE" IS '??????????????????';
COMMENT ON COLUMN "AGDOI"."AG_PERSON_INCOMP_AGENT_T"."PERSON_TYPE_CODE" IS '???????????????';
COMMENT ON COLUMN "AGDOI"."AG_PERSON_INCOMP_AGENT_T"."ID_CARD_NO" IS '??????????????????';
COMMENT ON COLUMN "AGDOI"."AG_PERSON_INCOMP_AGENT_T"."PRE_NAME_CODE" IS '????????????';
COMMENT ON COLUMN "AGDOI"."AG_PERSON_INCOMP_AGENT_T"."NAME_LASTNAME" IS '???????????';
COMMENT ON COLUMN "AGDOI"."AG_PERSON_INCOMP_AGENT_T"."IN_DATE" IS '??????????';
COMMENT ON COLUMN "AGDOI"."AG_PERSON_INCOMP_AGENT_T"."OUT_DATE" IS '?????????';
COMMENT ON COLUMN "AGDOI"."AG_PERSON_INCOMP_AGENT_T"."SHARE_NO" IS '?????????';
COMMENT ON COLUMN "AGDOI"."AG_PERSON_INCOMP_AGENT_T"."STATUS" IS '??????????????? A=active,C=cancle';
COMMENT ON COLUMN "AGDOI"."AG_PERSON_INCOMP_AGENT_T"."USER_ID" IS '?????????';
COMMENT ON COLUMN "AGDOI"."AG_PERSON_INCOMP_AGENT_T"."USER_DATE" IS '????????????';

-- ----------------------------
-- Indexes structure for table AG_PERSON_INCOMP_AGENT_T
-- ----------------------------
CREATE INDEX "AGDOI"."AG_PER_INC_AG_COMP_CODE_INX"
ON "AGDOI"."AG_PERSON_INCOMP_AGENT_T" ("COMPANY_CODE" ASC)
LOGGING;
CREATE INDEX "AGDOI"."AG_PER_INC_AG_ID_CARD_INX"
ON "AGDOI"."AG_PERSON_INCOMP_AGENT_T" ("ID_CARD_NO" ASC)
LOGGING;
CREATE INDEX "AGDOI"."AG_PER_INC_AG_IN_DATE_INX"
ON "AGDOI"."AG_PERSON_INCOMP_AGENT_T" ("IN_DATE" ASC)
LOGGING;
CREATE INDEX "AGDOI"."AG_PER_INC_AG_LICE_NO_INX"
ON "AGDOI"."AG_PERSON_INCOMP_AGENT_T" ("LICENSE_NO" ASC)
LOGGING;
CREATE INDEX "AGDOI"."AG_PER_INC_AG_OUT_DATE_INX"
ON "AGDOI"."AG_PERSON_INCOMP_AGENT_T" ("OUT_DATE" ASC)
LOGGING;
CREATE INDEX "AGDOI"."AG_PER_INC_AG_STATUS_INX"
ON "AGDOI"."AG_PERSON_INCOMP_AGENT_T" ("STATUS" ASC)
LOGGING;

-- ----------------------------
-- Triggers structure for table AG_PERSON_INCOMP_AGENT_T
-- ----------------------------
CREATE OR REPLACE TRIGGER "AGDOI"."AG_PERSON_INCOMP_AGENT_TRG" BEFORE INSERT OR UPDATE ON "AGDOI"."AG_PERSON_INCOMP_AGENT_T" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW
BEGIN
   :NEW.USER_ID  := GET_SYS_USER;
   :NEW.USER_DATE  := SYSDATE;
END;
-- ----------------------------
-- Primary Key structure for table AG_PERSON_INCOMP_AGENT_T
-- ----------------------------
ALTER TABLE "AGDOI"."AG_PERSON_INCOMP_AGENT_T" ADD PRIMARY KEY ("COMPANY_CODE", "LICENSE_NO", "IN_DATE");

-- ----------------------------
-- Foreign Key structure for table "AGDOI"."AG_PERSON_INCOMP_AGENT_T"
-- ----------------------------
ALTER TABLE "AGDOI"."AG_PERSON_INCOMP_AGENT_T" ADD FOREIGN KEY ("COMPANY_CODE") REFERENCES "ASDOI"."AS_COMPANY_T" ("COMP_CODE") ENABLE NOVALIDATE;
ALTER TABLE "AGDOI"."AG_PERSON_INCOMP_AGENT_T" ADD FOREIGN KEY ("LICENSE_TYPE_CODE") REFERENCES "AGDOI"."AG_LICENSE_TYPE_R" ("LICENSE_TYPE_CODE");
ALTER TABLE "AGDOI"."AG_PERSON_INCOMP_AGENT_T" ADD FOREIGN KEY ("PERSON_TYPE_CODE") REFERENCES "AGDOI"."AG_PERSON_TYPE_R" ("PERSON_TYPE_CODE");
ALTER TABLE "AGDOI"."AG_PERSON_INCOMP_AGENT_T" ADD FOREIGN KEY ("PRE_NAME_CODE") REFERENCES "GBDOI"."GB_PREFIX_R" ("PRE_CODE");
