/*
Navicat Oracle Data Transfer
Oracle Client Version : 11.2.0.3.0

Source Server         : AGDOI
Source Server Version : 90200
Source Host           : :1521
Source Schema         : AGDOI

Target Server Type    : ORACLE
Target Server Version : 90200
File Encoding         : 65001

Date: 2014-04-09 14:44:04
*/


-- ----------------------------
-- Table structure for AG_PERSONAL_T
-- ----------------------------

CREATE TABLE "AGDOI"."AG_PERSONAL_T" (
"ID_CARD_NO" VARCHAR2(13 BYTE) NOT NULL ,
"PRE_NAME_CODE" VARCHAR2(3 BYTE) NULL ,
"NAMES" VARCHAR2(50 BYTE) NULL ,
"LASTNAME" VARCHAR2(40 BYTE) NULL ,
"NATIONALITY" VARCHAR2(20 BYTE) NULL ,
"BIRTH_DATE" DATE NULL ,
"SEX" VARCHAR2(1 BYTE) NULL ,
"EDUCATION_CODE" VARCHAR2(2 BYTE) NULL ,
"ADDRESS1" VARCHAR2(60 BYTE) NULL ,
"ADDRESS2" VARCHAR2(60 BYTE) NULL ,
"AREA_CODE" VARCHAR2(8 BYTE) NULL ,
"PROVINCE_CODE" VARCHAR2(3 BYTE) NULL ,
"ZIPCODE" VARCHAR2(5 BYTE) NULL ,
"TELEPHONE" VARCHAR2(15 BYTE) NULL ,
"LOCAL_ADDRESS1" VARCHAR2(60 BYTE) NULL ,
"LOCAL_ADDRESS2" VARCHAR2(60 BYTE) NULL ,
"LOCAL_AREA_CODE" VARCHAR2(8 BYTE) NULL ,
"LOCAL_PROVINCE_CODE" VARCHAR2(3 BYTE) NULL ,
"LOCAL_ZIPCODE" VARCHAR2(5 BYTE) NULL ,
"LOCAL_TELEPHONE" VARCHAR2(15 BYTE) NULL ,
"USER_ID" VARCHAR2(15 BYTE) NULL ,
"USER_DATE" DATE NULL ,
"REMARK" VARCHAR2(500 BYTE) NULL ,
"UCOM_AGENT_ID" VARCHAR2(15 BYTE) NULL ,
"UCOM_AGENT_TYPE" VARCHAR2(2 BYTE) NULL ,
"NAME_CHG_DATE" DATE NULL ,
"E_MAIL" VARCHAR2(255 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "AGDOI"."AG_PERSONAL_T" IS '????????????';
COMMENT ON COLUMN "AGDOI"."AG_PERSONAL_T"."ID_CARD_NO" IS '??????????????????';
COMMENT ON COLUMN "AGDOI"."AG_PERSONAL_T"."PRE_NAME_CODE" IS '????????????';
COMMENT ON COLUMN "AGDOI"."AG_PERSONAL_T"."NAMES" IS '????';
COMMENT ON COLUMN "AGDOI"."AG_PERSONAL_T"."LASTNAME" IS '???????';
COMMENT ON COLUMN "AGDOI"."AG_PERSONAL_T"."NATIONALITY" IS '???????';
COMMENT ON COLUMN "AGDOI"."AG_PERSONAL_T"."BIRTH_DATE" IS '??????????????';
COMMENT ON COLUMN "AGDOI"."AG_PERSONAL_T"."SEX" IS '???  ? = ??????, ? = ???????';
COMMENT ON COLUMN "AGDOI"."AG_PERSONAL_T"."EDUCATION_CODE" IS '????????????????';
COMMENT ON COLUMN "AGDOI"."AG_PERSONAL_T"."ADDRESS1" IS '???????1';
COMMENT ON COLUMN "AGDOI"."AG_PERSONAL_T"."ADDRESS2" IS '???????2';
COMMENT ON COLUMN "AGDOI"."AG_PERSONAL_T"."AREA_CODE" IS '???????????';
COMMENT ON COLUMN "AGDOI"."AG_PERSONAL_T"."PROVINCE_CODE" IS '???????????';
COMMENT ON COLUMN "AGDOI"."AG_PERSONAL_T"."ZIPCODE" IS '????????????';
COMMENT ON COLUMN "AGDOI"."AG_PERSONAL_T"."TELEPHONE" IS '????????';
COMMENT ON COLUMN "AGDOI"."AG_PERSONAL_T"."LOCAL_ADDRESS1" IS '???????????????????1';
COMMENT ON COLUMN "AGDOI"."AG_PERSONAL_T"."LOCAL_ADDRESS2" IS '???????????????????2';
COMMENT ON COLUMN "AGDOI"."AG_PERSONAL_T"."LOCAL_AREA_CODE" IS '???????????????????????';
COMMENT ON COLUMN "AGDOI"."AG_PERSONAL_T"."LOCAL_PROVINCE_CODE" IS '???????????????????????';
COMMENT ON COLUMN "AGDOI"."AG_PERSONAL_T"."LOCAL_ZIPCODE" IS '????????????????????????';
COMMENT ON COLUMN "AGDOI"."AG_PERSONAL_T"."LOCAL_TELEPHONE" IS '????????????????????';
COMMENT ON COLUMN "AGDOI"."AG_PERSONAL_T"."USER_ID" IS '?????????';
COMMENT ON COLUMN "AGDOI"."AG_PERSONAL_T"."USER_DATE" IS '????????????';

-- ----------------------------
-- Indexes structure for table AG_PERSONAL_T
-- ----------------------------
CREATE INDEX "AGDOI"."AGIN_PERSONAL_EDU"
ON "AGDOI"."AG_PERSONAL_T" ("EDUCATION_CODE" ASC)
LOGGING;
CREATE INDEX "AGDOI"."AGIN_PERSONAL_LASTNAME"
ON "AGDOI"."AG_PERSONAL_T" ("LASTNAME" ASC)
LOGGING;
CREATE INDEX "AGDOI"."AGIN_PERSONAL_LPROVICE"
ON "AGDOI"."AG_PERSONAL_T" ("LOCAL_PROVINCE_CODE" ASC)
LOGGING;
CREATE INDEX "AGDOI"."AGIN_PERSONAL_NAMES"
ON "AGDOI"."AG_PERSONAL_T" ("NAMES" ASC)
LOGGING;

-- ----------------------------
-- Triggers structure for table AG_PERSONAL_T
-- ----------------------------
CREATE OR REPLACE TRIGGER "AGDOI"."AG_PERSONAL_TRG" BEFORE INSERT OR UPDATE ON "AGDOI"."AG_PERSONAL_T" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW
BEGIN
   :NEW.USER_ID := GET_SYS_USER;
   :NEW.USER_DATE  := SYSDATE;
                   If INSERTING Then
                       :NEW.NAME_CHG_DATE := SYSDATE;
                   Else
                       If :NEW.NAMES <> :OLD.NAMES Then
                           :NEW.NAME_CHG_DATE := SYSDATE;
                       ElsIf :NEW.LASTNAME <> :OLD.LASTNAME Then
                           :NEW.NAME_CHG_DATE := SYSDATE;
                       ElsIf :NEW.PRE_NAME_CODE <> :OLD.PRE_NAME_CODE Then
                           :NEW.NAME_CHG_DATE := SYSDATE;
                       End If;
                  End If;
END;
CREATE OR REPLACE TRIGGER "AGDOI"."AG_PERSONAL_UP_INCOMPAGENT_TRG" AFTER UPDATE ON "AGDOI"."AG_PERSONAL_T" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW
DECLARE
  v_flag  CHAR(1);
BEGIN
  IF :OLD.PRE_NAME_CODE <> :NEW.PRE_NAME_CODE OR
     :OLD.NAMES         <> :NEW.NAMES         OR
     :OLD.LASTNAME      <> :NEW.LASTNAME      THEN
     BEGIN
       SELECT 'T' INTO v_flag
       FROM   AG_PERSON_INCOMP_AGENT_T
       WHERE  ID_CARD_NO = :OLD.ID_CARD_NO;
     EXCEPTION
       WHEN TOO_MANY_ROWS THEN v_flag := 'T';
       WHEN NO_DATA_FOUND THEN v_flag := 'F';
       WHEN OTHERS        THEN v_flag := 'F';
     END;
     IF v_flag = 'T' THEN
        BEGIN
          UPDATE AG_PERSON_INCOMP_AGENT_T
          SET    PRE_NAME_CODE = :NEW.PRE_NAME_CODE
                ,NAME_LASTNAME = :NEW.NAMES||' '||:NEW.LASTNAME
          WHERE  ID_CARD_NO = :OLD.ID_CARD_NO;
        EXCEPTION WHEN OTHERS THEN NULL;
        END;
     END IF;
  END IF;
END;

-- ----------------------------
-- Checks structure for table AG_PERSONAL_T
-- ----------------------------
ALTER TABLE "AGDOI"."AG_PERSONAL_T" ADD CHECK (SEX  IN ('F','M'));

-- ----------------------------
-- Primary Key structure for table AG_PERSONAL_T
-- ----------------------------
ALTER TABLE "AGDOI"."AG_PERSONAL_T" ADD PRIMARY KEY ("ID_CARD_NO");

-- ----------------------------
-- Foreign Key structure for table "AGDOI"."AG_PERSONAL_T"
-- ----------------------------
ALTER TABLE "AGDOI"."AG_PERSONAL_T" ADD FOREIGN KEY ("EDUCATION_CODE") REFERENCES "AGDOI"."AG_EDUCATION_R" ("EDUCATION_CODE");
