/*
Navicat Oracle Data Transfer
Oracle Client Version : 11.2.0.3.0

Source Server         : AGDOI
Source Server Version : 90200
Source Host           : :1521
Source Schema         : AGDOI

Target Server Type    : ORACLE
Target Server Version : 90200
File Encoding         : 65001

Date: 2014-04-09 14:46:29
*/


-- ----------------------------
-- Table structure for AG_TRAIN_PERSON_T
-- ----------------------------

CREATE TABLE "AGDOI"."AG_TRAIN_PERSON_T" (
"TRAIN_CODE" VARCHAR2(10 BYTE) NOT NULL ,
"ID_CARD_NO" VARCHAR2(13 BYTE) NOT NULL ,
"PRE_NAME" VARCHAR2(40 BYTE) NULL ,
"NAMES" VARCHAR2(50 BYTE) NULL ,
"LASTNAME" VARCHAR2(40 BYTE) NULL ,
"LICENSE_NO" VARCHAR2(15 BYTE) NULL ,
"RESULT" VARCHAR2(1 BYTE) NULL ,
"USER_ID" VARCHAR2(15 BYTE) NULL ,
"USER_DATE" DATE NULL ,
"C_FLAG" VARCHAR2(1 BYTE) NULL ,
"E_FLAG" VARCHAR2(3 BYTE) NULL ,
"LICENSE_TYPE_CODE" VARCHAR2(2 BYTE) NOT NULL ,
"TRAIN_TIMES" NUMBER(2) NOT NULL ,
"TRAIN_DATE" DATE NOT NULL ,
"TRAIN_EXP_DATE" DATE NULL ,
"TRAIN_PERIOD" NUMBER(3) NULL ,
"PILAR_1" NUMBER(3) NULL ,
"PILAR_2" NUMBER(3) NULL ,
"PILAR_3" NUMBER(3) NULL ,
"TRAIN_TYPE" VARCHAR2(1 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "AGDOI"."AG_TRAIN_PERSON_T" IS '???????????????????????????? ??/??????????? ??? AG_LICENSE_T ';
COMMENT ON COLUMN "AGDOI"."AG_TRAIN_PERSON_T"."TRAIN_CODE" IS '???????????????';
COMMENT ON COLUMN "AGDOI"."AG_TRAIN_PERSON_T"."ID_CARD_NO" IS '??????????????';
COMMENT ON COLUMN "AGDOI"."AG_TRAIN_PERSON_T"."PRE_NAME" IS '????????????';
COMMENT ON COLUMN "AGDOI"."AG_TRAIN_PERSON_T"."NAMES" IS '????';
COMMENT ON COLUMN "AGDOI"."AG_TRAIN_PERSON_T"."LASTNAME" IS '????';
COMMENT ON COLUMN "AGDOI"."AG_TRAIN_PERSON_T"."LICENSE_NO" IS '??????????????';
COMMENT ON COLUMN "AGDOI"."AG_TRAIN_PERSON_T"."RESULT" IS '?????? P=????';
COMMENT ON COLUMN "AGDOI"."AG_TRAIN_PERSON_T"."USER_ID" IS '?????????????';
COMMENT ON COLUMN "AGDOI"."AG_TRAIN_PERSON_T"."USER_DATE" IS '?????????????????';
COMMENT ON COLUMN "AGDOI"."AG_TRAIN_PERSON_T"."C_FLAG" IS '??????????? X=??????????';
COMMENT ON COLUMN "AGDOI"."AG_TRAIN_PERSON_T"."E_FLAG" IS '????????????????????????/??????????/???????? ???????????? AG_TRAIN_SPEC_CASE_R';
COMMENT ON COLUMN "AGDOI"."AG_TRAIN_PERSON_T"."TRAIN_TYPE" IS 'T = Train , S = Samina';

-- ----------------------------
-- Indexes structure for table AG_TRAIN_PERSON_T
-- ----------------------------
CREATE INDEX "AGDOI"."AG_TRAIN_PERSON_T_ID"
ON "AGDOI"."AG_TRAIN_PERSON_T" ("ID_CARD_NO" ASC)
LOGGING;
CREATE INDEX "AGDOI"."AG_TRAIN_PERSON_T_ID2"
ON "AGDOI"."AG_TRAIN_PERSON_T" ("TRAIN_CODE" ASC)
LOGGING;
CREATE INDEX "AGDOI"."AG_TRAIN_PERSON_T_ID3"
ON "AGDOI"."AG_TRAIN_PERSON_T" ("NAMES" ASC)
LOGGING;
CREATE INDEX "AGDOI"."AG_TRAIN_PERSON_T_ID4"
ON "AGDOI"."AG_TRAIN_PERSON_T" ("LASTNAME" ASC)
LOGGING;

-- ----------------------------
-- Triggers structure for table AG_TRAIN_PERSON_T
-- ----------------------------
CREATE OR REPLACE TRIGGER "AGDOI"."AG_TRAIN_PERSON_T_TRG" BEFORE INSERT OR UPDATE ON "AGDOI"."AG_TRAIN_PERSON_T" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW
BEGIN
   :NEW.USER_ID := GET_SYS_USER;
   :NEW.USER_DATE := SYSDATE;
END;

-- ----------------------------
-- Checks structure for table AG_TRAIN_PERSON_T
-- ----------------------------
ALTER TABLE "AGDOI"."AG_TRAIN_PERSON_T" ADD CHECK ("TRAIN_CODE" IS NOT NULL);
ALTER TABLE "AGDOI"."AG_TRAIN_PERSON_T" ADD CHECK ("ID_CARD_NO" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table AG_TRAIN_PERSON_T
-- ----------------------------
ALTER TABLE "AGDOI"."AG_TRAIN_PERSON_T" ADD PRIMARY KEY ("TRAIN_CODE", "ID_CARD_NO", "LICENSE_TYPE_CODE", "TRAIN_TIMES", "TRAIN_DATE");
