using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IAS.DataServices.Payment
{
    public class APPR_BD_MOVEMENT
    {
        public String BUDGET_CODE { get; set; } //	VARCHAR2	(	20	)
        public String SECTION_CODE { get; set; } //	VARCHAR2	(	20	)
        public String PROJECT_CODE { get; set; } //	VARCHAR2	(	20	)
        public String ACTIVITY { get; set; } //	VARCHAR2	(	20	)
        public String BUD_ACCOUNT_CODE { get; set; } //	VARCHAR2	(	20	)
        public String ACCOUNT_CODE { get; set; } //	VARCHAR2	(	20	)
        public String PLAN_CODE { get; set; } //	VARCHAR2	(	20	)
        public String FUND_CODE { get; set; } //	VARCHAR2	(	20	)
        public String GROUP_SECTION { get; set; } //	VARCHAR2	(	20	)
        public String GROUP_ACTIVITY { get; set; } //	VARCHAR2	(	20	)
        public String MUAD_ACCOUNT { get; set; } //	VARCHAR2	(	20	)
        public String BUD_ACCOUNT_TYPE { get; set; } //	VARCHAR2	(	20	)
        public String STATUS { get; set; } //	VARCHAR2	(	2	)
        public String STATUS_APPROVE { get; set; } //	VARCHAR2	(	1	)
        public String STATUS_POST { get; set; } //	VARCHAR2	(	1	)
        public String DESCRIPTION { get; set; } //	VARCHAR2	(	255	)
        public String DESCRIPTION2 { get; set; } //	VARCHAR2	(	255	)
        public Decimal REQUEST_AMOUNT_A { get; set; } //	NUMBER	(	22	)
        public Decimal REQUEST_AMOUNT_R { get; set; } //	NUMBER	(	22	)
        public Decimal RETURN_AMOUNT_A { get; set; } //	NUMBER	(	22	)
        public Decimal RETURN_AMOUNT_R { get; set; } //	NUMBER	(	22	)
        public String BUDGET_REFERENCE { get; set; } //	VARCHAR2	(	200	)
        public Decimal TRI_21 { get; set; } //	NUMBER	(	22	)
        public Decimal TRO_22 { get; set; } //	NUMBER	(	22	)
        public Decimal ADD_25 { get; set; } //	NUMBER	(	22	)
        public Decimal RED_26 { get; set; } //	NUMBER	(	22	)
        public Decimal PR_A_31 { get; set; } //	NUMBER	(	22	)
        public Decimal PR_R_31 { get; set; } //	NUMBER	(	22	)
        public Decimal ESN_A_32 { get; set; } //	NUMBER	(	22	)
        public Decimal ESN_R_32 { get; set; } //	NUMBER	(	22	)
        public Decimal ESP_A_33 { get; set; } //	NUMBER	(	22	)
        public Decimal ESP_R_33 { get; set; } //	NUMBER	(	22	)
        public Decimal PO_A_41 { get; set; } //	NUMBER	(	22	)
        public Decimal PO_R_41 { get; set; } //	NUMBER	(	22	)
        public Decimal RO_A_42 { get; set; } //	NUMBER	(	22	)
        public Decimal RO_R_42 { get; set; } //	NUMBER	(	22	)
        public Decimal AP_A_43 { get; set; } //	NUMBER	(	22	)
        public Decimal AP_R_43 { get; set; } //	NUMBER	(	22	)
        public Decimal AR_A_44 { get; set; } //	NUMBER	(	22	)
        public Decimal AR_R_44 { get; set; } //	NUMBER	(	22	)
        public Decimal RCAR_A_48 { get; set; } //	NUMBER	(	22	)
        public Decimal RCAR_R_48 { get; set; } //	NUMBER	(	22	)
        public Decimal PA_A_51 { get; set; } //	NUMBER	(	22	)
        public Decimal PA_R_51 { get; set; } //	NUMBER	(	22	)
        public Decimal PAAP_A_52 { get; set; } //	NUMBER	(	22	)
        public Decimal PAAP_R_52 { get; set; } //	NUMBER	(	22	)
        public Decimal CLR_A_55 { get; set; } //	NUMBER	(	22	)
        public Decimal CLR_R_55 { get; set; } //	NUMBER	(	22	)
        public Decimal ADJ_A_52 { get; set; } //	NUMBER	(	22	)
        public Decimal ADJ_R_52 { get; set; } //	NUMBER	(	22	)
        public Decimal RC_A_80 { get; set; } //	NUMBER	(	22	)
        public Decimal RC_R_80 { get; set; } //	NUMBER	(	22	)
        public DateTime BALANCE_DATE { get; set; } //	DATE	(	7	)
        public DateTime BUD_YEAR { get; set; } //	DATE	(	7	)
        public Decimal PERIOD { get; set; } //	NUMBER	(	22	)
        public Decimal BRANCH_NO { get; set; } //	NUMBER	(	22	)
        public Decimal SYSTEM_NO { get; set; } //	NUMBER	(	22	)
        public String SYSTEM_CODE { get; set; } //	VARCHAR2	(	10	)
        public String SYSTEM_REF { get; set; } //	VARCHAR2	(	10	)
        public String DOC_TYPE { get; set; } //	VARCHAR2	(	5	)
        public String DOC_NO { get; set; } //	VARCHAR2	(	20	)
        public DateTime DOC_DATE { get; set; } //	DATE	(	7	)
        public String REF_DOC_TYPE { get; set; } //	VARCHAR2	(	5	)
        public String REF_DOC_NO { get; set; } //	VARCHAR2	(	20	)
        public DateTime REF_DOC_DATE { get; set; } //	DATE	(	7	)
        public Decimal SEQUENCE_GL { get; set; } //	NUMBER	(	22	)
        public Decimal BD_AMOUNT_A { get; set; } //	NUMBER	(	22	)
        public Decimal BD_AMOUNT_R { get; set; } //	NUMBER	(	22	)
        public Decimal TRAN_AMOUNT_A { get; set; } //	NUMBER	(	22	)
        public Decimal TRAN_AMOUNT_R { get; set; } //	NUMBER	(	22	)
        public Decimal RESERVE_AMOUNT_A { get; set; } //	NUMBER	(	22	)
        public Decimal RESERVE_AMOUNT_R { get; set; } //	NUMBER	(	22	)
        public Decimal USED_AMOUNT_A { get; set; } //	NUMBER	(	22	)
        public Decimal USED_AMOUNT_R { get; set; } //	NUMBER	(	22	)
        public Decimal PAYMENT_AMOUNT_A { get; set; } //	NUMBER	(	22	)
        public Decimal PAYMENT_AMOUNT_R { get; set; } //	NUMBER	(	22	)
        public Decimal RECEIVE_AMOUNT_A { get; set; } //	NUMBER	(	22	)
        public Decimal RECEIVE_AMOUNT_R { get; set; } //	NUMBER	(	22	)
    }
}